language: java
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
script:  ./mvnw clean install -Ptravis  -B -V
script:  ./mvnw clean install -Ptesting  -B -V
