language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.6"
  apt:
    packages:
      - oracle-java8-installer
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
sudo: false
script:  ./mvnw clean install -Ptesting  -B -V
