language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-de
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.6
before_script:
  - psql -U postgres < etc/prepare-db-for-travis.sql
  - psql -c 'select * from version();' -U kandidatentest
sudo: false
script:  ./mvnw clean site site:deploy -Ptravis  -B -V
