language: java
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
before_script: rm -rf $HOME/.m2/wrapper/* $HOME/.m2/repository/*
script:  ./mvnw clean install site -Ptravis  -B -V
