INSERT INTO wohnort (id,wohnort) VALUES (1, 'Moosburg a.d.Isar' );
INSERT INTO wohnort (id,wohnort) VALUES (2, 'Mühldorf a.Inn' );
INSERT INTO wohnort (id,wohnort) VALUES (3, 'Staufen im Breisgau' );
INSERT INTO wohnort (id,wohnort) VALUES (4, 'Speyer' );
INSERT INTO wohnort (id,wohnort) VALUES (5, 'Gleißenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (6, 'Porta Westfalica' );
INSERT INTO wohnort (id,wohnort) VALUES (7, 'Lohr a.Main' );
INSERT INTO wohnort (id,wohnort) VALUES (8, 'Putgarten' );
INSERT INTO wohnort (id,wohnort) VALUES (9, 'Tutzing' );
INSERT INTO wohnort (id,wohnort) VALUES (10, 'Erdweg' );
INSERT INTO wohnort (id,wohnort) VALUES (11, 'Nördlingen' );
INSERT INTO wohnort (id,wohnort) VALUES (12, 'Lindewitt' );
INSERT INTO wohnort (id,wohnort) VALUES (13, 'Salzgitter' );
INSERT INTO wohnort (id,wohnort) VALUES (14, 'Lichterfeld-Schacksdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (15, 'Künzing' );
INSERT INTO wohnort (id,wohnort) VALUES (16, 'Gohrisch' );
INSERT INTO wohnort (id,wohnort) VALUES (17, 'Neubrandenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (18, 'Reichshof' );
INSERT INTO wohnort (id,wohnort) VALUES (19, 'Crawinkel' );
INSERT INTO wohnort (id,wohnort) VALUES (20, 'Königswinter' );
INSERT INTO wohnort (id,wohnort) VALUES (21, 'Oberkotzau' );
INSERT INTO wohnort (id,wohnort) VALUES (22, 'Offenbach am Main' );
INSERT INTO wohnort (id,wohnort) VALUES (23, 'Bubenheim' );
INSERT INTO wohnort (id,wohnort) VALUES (24, 'Bendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (25, 'Niedernhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (26, 'Schmalkalden' );
INSERT INTO wohnort (id,wohnort) VALUES (27, 'Burgsalach' );
INSERT INTO wohnort (id,wohnort) VALUES (28, 'Weyhe' );
INSERT INTO wohnort (id,wohnort) VALUES (29, 'Taunusstein' );
INSERT INTO wohnort (id,wohnort) VALUES (30, 'Elmshorn' );
INSERT INTO wohnort (id,wohnort) VALUES (31, 'Spaichingen' );
INSERT INTO wohnort (id,wohnort) VALUES (32, 'Reinholterode' );
INSERT INTO wohnort (id,wohnort) VALUES (33, 'Walddorfhäslach' );
INSERT INTO wohnort (id,wohnort) VALUES (34, 'Bad Waldsee' );
INSERT INTO wohnort (id,wohnort) VALUES (35, 'Mundelsheim' );
INSERT INTO wohnort (id,wohnort) VALUES (36, 'Oranienbaum-Wörlitz' );
INSERT INTO wohnort (id,wohnort) VALUES (37, 'Singen (Hohentwiel)' );
INSERT INTO wohnort (id,wohnort) VALUES (38, 'Oberhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (39, 'Alsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (40, 'Brachttal' );
INSERT INTO wohnort (id,wohnort) VALUES (41, 'Namborn' );
INSERT INTO wohnort (id,wohnort) VALUES (42, 'Blankenfelde-Mahlow' );
INSERT INTO wohnort (id,wohnort) VALUES (43, 'Külz (Hunsrück)' );
INSERT INTO wohnort (id,wohnort) VALUES (44, 'Aschau a.Inn' );
INSERT INTO wohnort (id,wohnort) VALUES (45, 'Simbach' );
INSERT INTO wohnort (id,wohnort) VALUES (46, 'Untergruppenbach' );
INSERT INTO wohnort (id,wohnort) VALUES (47, 'Starnberg' );
INSERT INTO wohnort (id,wohnort) VALUES (48, 'Wassertrüdingen' );
INSERT INTO wohnort (id,wohnort) VALUES (49, 'Werder (Havel)' );
INSERT INTO wohnort (id,wohnort) VALUES (50, 'Hildburghausen' );
INSERT INTO wohnort (id,wohnort) VALUES (51, 'Korntal-Münchingen' );
INSERT INTO wohnort (id,wohnort) VALUES (52, 'Altensteig' );
INSERT INTO wohnort (id,wohnort) VALUES (53, 'Mühlhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (54, 'Blindheim' );
INSERT INTO wohnort (id,wohnort) VALUES (55, 'Mönchengladbach' );
INSERT INTO wohnort (id,wohnort) VALUES (56, 'Gauting' );
INSERT INTO wohnort (id,wohnort) VALUES (57, 'Prüm' );
INSERT INTO wohnort (id,wohnort) VALUES (58, 'Nürnberg' );
INSERT INTO wohnort (id,wohnort) VALUES (59, 'Borchen' );
INSERT INTO wohnort (id,wohnort) VALUES (60, 'Schleswig' );
INSERT INTO wohnort (id,wohnort) VALUES (61, 'Göttingen' );
INSERT INTO wohnort (id,wohnort) VALUES (62, 'Bosau' );
INSERT INTO wohnort (id,wohnort) VALUES (63, 'Meerane' );
INSERT INTO wohnort (id,wohnort) VALUES (64, 'Görlitz' );
INSERT INTO wohnort (id,wohnort) VALUES (65, 'Ihringen' );
INSERT INTO wohnort (id,wohnort) VALUES (66, 'Hattingen' );
INSERT INTO wohnort (id,wohnort) VALUES (67, 'Frankenberg (Eder)' );
INSERT INTO wohnort (id,wohnort) VALUES (68, 'Schriesheim' );
INSERT INTO wohnort (id,wohnort) VALUES (69, 'Murr' );
INSERT INTO wohnort (id,wohnort) VALUES (70, 'Brackel' );
INSERT INTO wohnort (id,wohnort) VALUES (71, 'Biberach an der Riß' );
INSERT INTO wohnort (id,wohnort) VALUES (72, 'Saalstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (73, 'Neuenkirchen-Vörden' );
INSERT INTO wohnort (id,wohnort) VALUES (74, 'Bad Frankenhausen/Kyffhäuser' );
INSERT INTO wohnort (id,wohnort) VALUES (75, 'Cham' );
INSERT INTO wohnort (id,wohnort) VALUES (76, 'Sengenthal' );
INSERT INTO wohnort (id,wohnort) VALUES (77, 'Finsterwalde' );
INSERT INTO wohnort (id,wohnort) VALUES (78, 'Darmstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (79, 'Bad Schandau' );
INSERT INTO wohnort (id,wohnort) VALUES (80, 'Stepenitztal' );
INSERT INTO wohnort (id,wohnort) VALUES (81, 'Erkelenz' );
INSERT INTO wohnort (id,wohnort) VALUES (82, 'Völklingen' );
INSERT INTO wohnort (id,wohnort) VALUES (83, 'Lehrte' );
INSERT INTO wohnort (id,wohnort) VALUES (84, 'Kulmbach' );
INSERT INTO wohnort (id,wohnort) VALUES (85, 'Dohna' );
INSERT INTO wohnort (id,wohnort) VALUES (86, 'Heppenheim (Bergstraße)' );
INSERT INTO wohnort (id,wohnort) VALUES (87, 'Hoppegarten' );
INSERT INTO wohnort (id,wohnort) VALUES (88, 'Ditzingen' );
INSERT INTO wohnort (id,wohnort) VALUES (89, 'Bickenbach' );
INSERT INTO wohnort (id,wohnort) VALUES (90, 'Warburg' );
INSERT INTO wohnort (id,wohnort) VALUES (91, 'Preetz' );
INSERT INTO wohnort (id,wohnort) VALUES (92, 'Raesfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (93, 'Haldensleben' );
INSERT INTO wohnort (id,wohnort) VALUES (94, 'Zellertal' );
INSERT INTO wohnort (id,wohnort) VALUES (95, 'Essen' );
INSERT INTO wohnort (id,wohnort) VALUES (96, 'Langenhagen' );
INSERT INTO wohnort (id,wohnort) VALUES (97, 'Volkach' );
INSERT INTO wohnort (id,wohnort) VALUES (98, 'Löningen' );
INSERT INTO wohnort (id,wohnort) VALUES (99, 'Frankfurt am Main' );
INSERT INTO wohnort (id,wohnort) VALUES (100, 'Duderstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (101, 'Herne' );
INSERT INTO wohnort (id,wohnort) VALUES (102, 'Aschaffenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (103, 'Hude (Oldb)' );
INSERT INTO wohnort (id,wohnort) VALUES (104, 'Ottersberg' );
INSERT INTO wohnort (id,wohnort) VALUES (105, 'Eningen unter Achalm' );
INSERT INTO wohnort (id,wohnort) VALUES (106, 'Höchstadt a.d.Aisch' );
INSERT INTO wohnort (id,wohnort) VALUES (107, 'Puchheim' );
INSERT INTO wohnort (id,wohnort) VALUES (108, 'Albstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (109, 'Zweiflingen' );
INSERT INTO wohnort (id,wohnort) VALUES (110, 'Waldkirch' );
INSERT INTO wohnort (id,wohnort) VALUES (111, 'Schmölln-Putzkau' );
INSERT INTO wohnort (id,wohnort) VALUES (112, 'Hochdonn' );
INSERT INTO wohnort (id,wohnort) VALUES (113, 'Konstanz' );
INSERT INTO wohnort (id,wohnort) VALUES (114, 'Wallerfangen' );
INSERT INTO wohnort (id,wohnort) VALUES (115, 'Oranienburg' );
INSERT INTO wohnort (id,wohnort) VALUES (116, 'Rückersdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (117, 'Hiddenhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (118, 'Hamminkeln' );
INSERT INTO wohnort (id,wohnort) VALUES (119, 'Bad Essen' );
INSERT INTO wohnort (id,wohnort) VALUES (120, 'Rheda-Wiedenbrück' );
INSERT INTO wohnort (id,wohnort) VALUES (121, 'Siebeneichen' );
INSERT INTO wohnort (id,wohnort) VALUES (122, 'Werne' );
INSERT INTO wohnort (id,wohnort) VALUES (123, 'Wilhelmshaven' );
INSERT INTO wohnort (id,wohnort) VALUES (124, 'Bad Iburg' );
INSERT INTO wohnort (id,wohnort) VALUES (125, 'Gomadingen' );
INSERT INTO wohnort (id,wohnort) VALUES (126, 'Fehmarn' );
INSERT INTO wohnort (id,wohnort) VALUES (127, 'Zweibrücken' );
INSERT INTO wohnort (id,wohnort) VALUES (128, 'Potsdam' );
INSERT INTO wohnort (id,wohnort) VALUES (129, 'Waibstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (130, 'Neuental' );
INSERT INTO wohnort (id,wohnort) VALUES (131, 'Peißenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (132, 'Mittweida' );
INSERT INTO wohnort (id,wohnort) VALUES (133, 'Lingen (Ems)' );
INSERT INTO wohnort (id,wohnort) VALUES (134, 'Forchheim' );
INSERT INTO wohnort (id,wohnort) VALUES (135, 'Mühlheim am Main' );
INSERT INTO wohnort (id,wohnort) VALUES (136, 'Bitterfeld-Wolfen' );
INSERT INTO wohnort (id,wohnort) VALUES (137, 'Munster' );
INSERT INTO wohnort (id,wohnort) VALUES (138, 'Losheim am See' );
INSERT INTO wohnort (id,wohnort) VALUES (139, 'Freiberg am Neckar' );
INSERT INTO wohnort (id,wohnort) VALUES (140, 'Teningen' );
INSERT INTO wohnort (id,wohnort) VALUES (141, 'Kutzenhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (142, 'Vierlinden' );
INSERT INTO wohnort (id,wohnort) VALUES (143, 'Havelaue' );
INSERT INTO wohnort (id,wohnort) VALUES (144, 'Oberursel (Taunus)' );
INSERT INTO wohnort (id,wohnort) VALUES (145, 'Eschborn' );
INSERT INTO wohnort (id,wohnort) VALUES (146, 'Peiting' );
INSERT INTO wohnort (id,wohnort) VALUES (147, 'Elende' );
INSERT INTO wohnort (id,wohnort) VALUES (148, 'Wiehl' );
INSERT INTO wohnort (id,wohnort) VALUES (149, 'Lage' );
INSERT INTO wohnort (id,wohnort) VALUES (150, 'Oberharz am Brocken' );
INSERT INTO wohnort (id,wohnort) VALUES (151, 'Marburg' );
INSERT INTO wohnort (id,wohnort) VALUES (152, 'Schweich' );
INSERT INTO wohnort (id,wohnort) VALUES (153, 'Böblingen' );
INSERT INTO wohnort (id,wohnort) VALUES (154, 'Oßling' );
INSERT INTO wohnort (id,wohnort) VALUES (155, 'Müllrose' );
INSERT INTO wohnort (id,wohnort) VALUES (156, 'Schömberg' );
INSERT INTO wohnort (id,wohnort) VALUES (157, 'Sulzbach (Taunus)' );
INSERT INTO wohnort (id,wohnort) VALUES (158, 'Höpfingen' );
INSERT INTO wohnort (id,wohnort) VALUES (159, 'Wörth am Rhein' );
INSERT INTO wohnort (id,wohnort) VALUES (160, 'Steinbach (Taunus)' );
INSERT INTO wohnort (id,wohnort) VALUES (161, 'Aschheim' );
INSERT INTO wohnort (id,wohnort) VALUES (162, 'Heilbad Heiligenstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (163, 'Calw' );
INSERT INTO wohnort (id,wohnort) VALUES (164, 'Neustadt b.Coburg' );
INSERT INTO wohnort (id,wohnort) VALUES (165, 'Fränkisch-Crumbach' );
INSERT INTO wohnort (id,wohnort) VALUES (166, 'Fredersdorf-Vogelsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (167, 'Waghäusel' );
INSERT INTO wohnort (id,wohnort) VALUES (168, 'Münsterhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (169, 'Freiburg' );
INSERT INTO wohnort (id,wohnort) VALUES (170, 'Möser' );
INSERT INTO wohnort (id,wohnort) VALUES (171, 'Pyrbaum' );
INSERT INTO wohnort (id,wohnort) VALUES (172, 'Loitz' );
INSERT INTO wohnort (id,wohnort) VALUES (173, 'Umkirch' );
INSERT INTO wohnort (id,wohnort) VALUES (174, 'Hohenstein-Ernstthal' );
INSERT INTO wohnort (id,wohnort) VALUES (175, 'Lalling' );
INSERT INTO wohnort (id,wohnort) VALUES (176, 'Walsleben' );
INSERT INTO wohnort (id,wohnort) VALUES (177, 'Roßdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (178, 'Backnang' );
INSERT INTO wohnort (id,wohnort) VALUES (179, 'Trabitz' );
INSERT INTO wohnort (id,wohnort) VALUES (180, 'Recklinghausen' );
INSERT INTO wohnort (id,wohnort) VALUES (181, 'Drensteinfurt' );
INSERT INTO wohnort (id,wohnort) VALUES (182, 'Burbach' );
INSERT INTO wohnort (id,wohnort) VALUES (183, 'Sulzbach-Rosenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (184, 'Edling' );
INSERT INTO wohnort (id,wohnort) VALUES (185, 'Weißenburg i.Bay.' );
INSERT INTO wohnort (id,wohnort) VALUES (186, 'Schwetzingen' );
INSERT INTO wohnort (id,wohnort) VALUES (187, 'Griesheim' );
INSERT INTO wohnort (id,wohnort) VALUES (188, 'Hitzhofen' );
INSERT INTO wohnort (id,wohnort) VALUES (189, 'Ribnitz-Damgarten' );
INSERT INTO wohnort (id,wohnort) VALUES (190, 'Raubling' );
INSERT INTO wohnort (id,wohnort) VALUES (191, 'Rudersberg' );
INSERT INTO wohnort (id,wohnort) VALUES (192, 'Birkenwerder' );
INSERT INTO wohnort (id,wohnort) VALUES (193, 'Haan' );
INSERT INTO wohnort (id,wohnort) VALUES (194, 'Traunstein' );
INSERT INTO wohnort (id,wohnort) VALUES (195, 'Schalkau' );
INSERT INTO wohnort (id,wohnort) VALUES (196, 'Datteln' );
INSERT INTO wohnort (id,wohnort) VALUES (197, 'Bad Wildungen' );
INSERT INTO wohnort (id,wohnort) VALUES (198, 'Boostedt' );
INSERT INTO wohnort (id,wohnort) VALUES (199, 'Langenfeld (Rheinland)' );
INSERT INTO wohnort (id,wohnort) VALUES (200, 'Altenkirchen (Westerwald)' );
INSERT INTO wohnort (id,wohnort) VALUES (201, 'Zirndorf' );
INSERT INTO wohnort (id,wohnort) VALUES (202, 'Fürstenfeldbruck' );
INSERT INTO wohnort (id,wohnort) VALUES (203, 'Reichling' );
INSERT INTO wohnort (id,wohnort) VALUES (204, 'Langewiesen' );
INSERT INTO wohnort (id,wohnort) VALUES (205, 'Bruchköbel' );
INSERT INTO wohnort (id,wohnort) VALUES (206, 'Dornstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (207, 'Neustadt an der Weinstraße' );
INSERT INTO wohnort (id,wohnort) VALUES (208, 'Weingarten (Baden)' );
INSERT INTO wohnort (id,wohnort) VALUES (209, 'Oldenburg (Oldenburg)' );
INSERT INTO wohnort (id,wohnort) VALUES (210, 'Durach' );
INSERT INTO wohnort (id,wohnort) VALUES (211, 'Schwebheim' );
INSERT INTO wohnort (id,wohnort) VALUES (212, 'Blaustein' );
INSERT INTO wohnort (id,wohnort) VALUES (213, 'Clausthal-Zellerfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (214, 'Laatzen' );
INSERT INTO wohnort (id,wohnort) VALUES (215, 'Gelnhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (216, 'Sankt Augustin' );
INSERT INTO wohnort (id,wohnort) VALUES (217, 'Cremlingen' );
INSERT INTO wohnort (id,wohnort) VALUES (218, 'Horstmar' );
INSERT INTO wohnort (id,wohnort) VALUES (219, 'Achberg' );
INSERT INTO wohnort (id,wohnort) VALUES (220, 'Höhr-Grenzhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (221, 'Pelm' );
INSERT INTO wohnort (id,wohnort) VALUES (222, 'Bochum' );
INSERT INTO wohnort (id,wohnort) VALUES (223, 'Forst (Lausitz)' );
INSERT INTO wohnort (id,wohnort) VALUES (224, 'Bad Dürkheim' );
INSERT INTO wohnort (id,wohnort) VALUES (225, 'Pätow-Steegen' );
INSERT INTO wohnort (id,wohnort) VALUES (226, 'Dingolfing' );
INSERT INTO wohnort (id,wohnort) VALUES (227, 'Arnsberg' );
INSERT INTO wohnort (id,wohnort) VALUES (228, 'Leuna' );
INSERT INTO wohnort (id,wohnort) VALUES (229, 'Schöneiche bei Berlin' );
INSERT INTO wohnort (id,wohnort) VALUES (230, 'Bad Salzuflen' );
INSERT INTO wohnort (id,wohnort) VALUES (231, 'Schwäbisch Gmünd' );
INSERT INTO wohnort (id,wohnort) VALUES (232, 'Olpe' );
INSERT INTO wohnort (id,wohnort) VALUES (233, 'Barnstorf' );
INSERT INTO wohnort (id,wohnort) VALUES (234, 'Arzfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (235, 'Chamerau' );
INSERT INTO wohnort (id,wohnort) VALUES (236, 'Dragun' );
INSERT INTO wohnort (id,wohnort) VALUES (237, 'Asbach-Bäumenheim' );
INSERT INTO wohnort (id,wohnort) VALUES (238, 'Floh-Seligenthal' );
INSERT INTO wohnort (id,wohnort) VALUES (239, 'Günzburg' );
INSERT INTO wohnort (id,wohnort) VALUES (240, 'Niederhorbach' );
INSERT INTO wohnort (id,wohnort) VALUES (241, 'Wittlich' );
INSERT INTO wohnort (id,wohnort) VALUES (242, 'Mühltal' );
INSERT INTO wohnort (id,wohnort) VALUES (243, 'Jena' );
INSERT INTO wohnort (id,wohnort) VALUES (244, 'Emsdetten' );
INSERT INTO wohnort (id,wohnort) VALUES (245, 'Hammelburg' );
INSERT INTO wohnort (id,wohnort) VALUES (246, 'Straelen' );
INSERT INTO wohnort (id,wohnort) VALUES (247, 'Friedberg' );
INSERT INTO wohnort (id,wohnort) VALUES (248, 'Metelen' );
INSERT INTO wohnort (id,wohnort) VALUES (249, 'Quedlinburg' );
INSERT INTO wohnort (id,wohnort) VALUES (250, 'Altenstadt a.d.Waldnaab' );
INSERT INTO wohnort (id,wohnort) VALUES (251, 'Lich' );
INSERT INTO wohnort (id,wohnort) VALUES (252, 'Eutingen im Gäu' );
INSERT INTO wohnort (id,wohnort) VALUES (253, 'Berkholz-Meyenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (254, 'Gronau (Westf.)' );
INSERT INTO wohnort (id,wohnort) VALUES (255, 'Niederkirchen bei Deidesheim' );
INSERT INTO wohnort (id,wohnort) VALUES (256, 'Gaukönigshofen' );
INSERT INTO wohnort (id,wohnort) VALUES (257, 'Idstein' );
INSERT INTO wohnort (id,wohnort) VALUES (258, 'Herzogenaurach' );
INSERT INTO wohnort (id,wohnort) VALUES (259, 'Lörrach' );
INSERT INTO wohnort (id,wohnort) VALUES (260, 'Ellwangen (Jagst)' );
INSERT INTO wohnort (id,wohnort) VALUES (261, 'Schneeberg' );
INSERT INTO wohnort (id,wohnort) VALUES (262, 'Märkische Heide' );
INSERT INTO wohnort (id,wohnort) VALUES (263, 'Walsrode' );
INSERT INTO wohnort (id,wohnort) VALUES (264, 'Krummhörn' );
INSERT INTO wohnort (id,wohnort) VALUES (265, 'Hirschberg an der Bergstraße' );
INSERT INTO wohnort (id,wohnort) VALUES (266, 'Eberbach' );
INSERT INTO wohnort (id,wohnort) VALUES (267, 'Bad Rothenfelde' );
INSERT INTO wohnort (id,wohnort) VALUES (268, 'Lohe-Rickelshof' );
INSERT INTO wohnort (id,wohnort) VALUES (269, 'Schönwalde-Glien' );
INSERT INTO wohnort (id,wohnort) VALUES (270, 'Ansbach' );
INSERT INTO wohnort (id,wohnort) VALUES (271, 'Wittenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (272, 'Werl' );
INSERT INTO wohnort (id,wohnort) VALUES (273, 'Grevenbroich' );
INSERT INTO wohnort (id,wohnort) VALUES (274, 'Rostock' );
INSERT INTO wohnort (id,wohnort) VALUES (275, 'Kirchen (Sieg)' );
INSERT INTO wohnort (id,wohnort) VALUES (276, 'Magdeburg' );
INSERT INTO wohnort (id,wohnort) VALUES (277, 'Allmendingen' );
INSERT INTO wohnort (id,wohnort) VALUES (278, 'Vaihingen an der Enz' );
INSERT INTO wohnort (id,wohnort) VALUES (279, 'Kirchdorf a.Inn' );
INSERT INTO wohnort (id,wohnort) VALUES (280, 'Remscheid' );
INSERT INTO wohnort (id,wohnort) VALUES (281, 'Rheinsberg' );
INSERT INTO wohnort (id,wohnort) VALUES (282, 'Sondershausen' );
INSERT INTO wohnort (id,wohnort) VALUES (283, 'Gemmingen' );
INSERT INTO wohnort (id,wohnort) VALUES (284, 'Kleve' );
INSERT INTO wohnort (id,wohnort) VALUES (285, 'Bad Soden am Taunus' );
INSERT INTO wohnort (id,wohnort) VALUES (286, 'Hanau' );
INSERT INTO wohnort (id,wohnort) VALUES (287, 'Witzenhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (288, 'Auerbach/Vogtl.' );
INSERT INTO wohnort (id,wohnort) VALUES (289, 'Ochsenfurt' );
INSERT INTO wohnort (id,wohnort) VALUES (290, 'Friesack' );
INSERT INTO wohnort (id,wohnort) VALUES (291, 'Bad Kissingen' );
INSERT INTO wohnort (id,wohnort) VALUES (292, 'Dahme' );
INSERT INTO wohnort (id,wohnort) VALUES (293, 'Lugau/Erzgeb.' );
INSERT INTO wohnort (id,wohnort) VALUES (294, 'Pfungstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (295, 'Gornau/Erzgeb.' );
INSERT INTO wohnort (id,wohnort) VALUES (296, 'Wildau' );
INSERT INTO wohnort (id,wohnort) VALUES (297, 'Vechta' );
INSERT INTO wohnort (id,wohnort) VALUES (298, 'Delitzsch' );
INSERT INTO wohnort (id,wohnort) VALUES (299, 'Siegburg' );
INSERT INTO wohnort (id,wohnort) VALUES (300, 'Bad Pyrmont' );
INSERT INTO wohnort (id,wohnort) VALUES (301, 'Freising' );
INSERT INTO wohnort (id,wohnort) VALUES (302, 'Dettum' );
INSERT INTO wohnort (id,wohnort) VALUES (303, 'Laufen' );
INSERT INTO wohnort (id,wohnort) VALUES (304, 'Martensrade' );
INSERT INTO wohnort (id,wohnort) VALUES (305, 'München' );
INSERT INTO wohnort (id,wohnort) VALUES (306, 'Schwalmtal' );
INSERT INTO wohnort (id,wohnort) VALUES (307, 'Lemgo' );
INSERT INTO wohnort (id,wohnort) VALUES (308, 'Markkleeberg' );
INSERT INTO wohnort (id,wohnort) VALUES (309, 'Burg' );
INSERT INTO wohnort (id,wohnort) VALUES (310, 'Bad Segeberg' );
INSERT INTO wohnort (id,wohnort) VALUES (311, 'Bühlertal' );
INSERT INTO wohnort (id,wohnort) VALUES (312, 'Werther (Westf.)' );
INSERT INTO wohnort (id,wohnort) VALUES (313, 'Einbeck' );
INSERT INTO wohnort (id,wohnort) VALUES (314, 'Langwedel' );
INSERT INTO wohnort (id,wohnort) VALUES (315, 'Buxtehude' );
INSERT INTO wohnort (id,wohnort) VALUES (316, 'Spantekow' );
INSERT INTO wohnort (id,wohnort) VALUES (317, 'Künzelsau' );
INSERT INTO wohnort (id,wohnort) VALUES (318, 'Tauberbischofsheim' );
INSERT INTO wohnort (id,wohnort) VALUES (319, 'Allensbach' );
INSERT INTO wohnort (id,wohnort) VALUES (320, 'Straubing' );
INSERT INTO wohnort (id,wohnort) VALUES (321, 'Weinheim' );
INSERT INTO wohnort (id,wohnort) VALUES (322, 'Königsbronn' );
INSERT INTO wohnort (id,wohnort) VALUES (323, 'Eitensheim' );
INSERT INTO wohnort (id,wohnort) VALUES (324, 'Witten' );
INSERT INTO wohnort (id,wohnort) VALUES (325, 'Baiern' );
INSERT INTO wohnort (id,wohnort) VALUES (326, 'Grünendeich' );
INSERT INTO wohnort (id,wohnort) VALUES (327, 'Sulzbach a.Main' );
INSERT INTO wohnort (id,wohnort) VALUES (328, 'Homburg' );
INSERT INTO wohnort (id,wohnort) VALUES (329, 'Gerbrunn' );
INSERT INTO wohnort (id,wohnort) VALUES (330, 'Warendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (331, 'Homberg (Ohm)' );
INSERT INTO wohnort (id,wohnort) VALUES (332, 'Korschenbroich' );
INSERT INTO wohnort (id,wohnort) VALUES (333, 'Neuruppin' );
INSERT INTO wohnort (id,wohnort) VALUES (334, 'Kirchberg an der Iller' );
INSERT INTO wohnort (id,wohnort) VALUES (335, 'Trebbin' );
INSERT INTO wohnort (id,wohnort) VALUES (336, 'Strande' );
INSERT INTO wohnort (id,wohnort) VALUES (337, 'Gladbeck' );
INSERT INTO wohnort (id,wohnort) VALUES (338, 'Wülfrath' );
INSERT INTO wohnort (id,wohnort) VALUES (339, 'Windhagen' );
INSERT INTO wohnort (id,wohnort) VALUES (340, 'Haibach' );
INSERT INTO wohnort (id,wohnort) VALUES (341, 'Hof' );
INSERT INTO wohnort (id,wohnort) VALUES (342, 'Schleiden' );
INSERT INTO wohnort (id,wohnort) VALUES (343, 'Ennigerloh' );
INSERT INTO wohnort (id,wohnort) VALUES (344, 'Trostberg' );
INSERT INTO wohnort (id,wohnort) VALUES (345, 'Fürstenwalde/Spree' );
INSERT INTO wohnort (id,wohnort) VALUES (346, 'Laufach' );
INSERT INTO wohnort (id,wohnort) VALUES (347, 'Viernheim' );
INSERT INTO wohnort (id,wohnort) VALUES (348, 'Kasseedorf' );
INSERT INTO wohnort (id,wohnort) VALUES (349, 'Castrop-Rauxel' );
INSERT INTO wohnort (id,wohnort) VALUES (350, 'Marlow' );
INSERT INTO wohnort (id,wohnort) VALUES (351, 'Ludwigsburg' );
INSERT INTO wohnort (id,wohnort) VALUES (352, 'Frankfurt (Oder)' );
INSERT INTO wohnort (id,wohnort) VALUES (353, 'Gundelfingen a.d.Donau' );
INSERT INTO wohnort (id,wohnort) VALUES (354, 'Brandis' );
INSERT INTO wohnort (id,wohnort) VALUES (355, 'Satow' );
INSERT INTO wohnort (id,wohnort) VALUES (356, 'Illerich' );
INSERT INTO wohnort (id,wohnort) VALUES (357, 'Miltenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (358, 'Lahr/Schwarzwald' );
INSERT INTO wohnort (id,wohnort) VALUES (359, 'Leinefelde-Worbis' );
INSERT INTO wohnort (id,wohnort) VALUES (360, 'Seth' );
INSERT INTO wohnort (id,wohnort) VALUES (361, 'Wünschendorf/Elster' );
INSERT INTO wohnort (id,wohnort) VALUES (362, 'Wertheim' );
INSERT INTO wohnort (id,wohnort) VALUES (363, 'Königslutter am Elm' );
INSERT INTO wohnort (id,wohnort) VALUES (364, 'Weiler' );
INSERT INTO wohnort (id,wohnort) VALUES (365, 'Altdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (366, 'Maring-Noviand' );
INSERT INTO wohnort (id,wohnort) VALUES (367, 'Gummersbach' );
INSERT INTO wohnort (id,wohnort) VALUES (368, 'Welver' );
INSERT INTO wohnort (id,wohnort) VALUES (369, 'Fürstenberg/Havel' );
INSERT INTO wohnort (id,wohnort) VALUES (370, 'Uetersen' );
INSERT INTO wohnort (id,wohnort) VALUES (371, 'Hennigsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (372, 'Schwalmstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (373, 'Medebach' );
INSERT INTO wohnort (id,wohnort) VALUES (374, 'Solingen' );
INSERT INTO wohnort (id,wohnort) VALUES (375, 'Tecklenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (376, 'Lindlar' );
INSERT INTO wohnort (id,wohnort) VALUES (377, 'Eschweiler' );
INSERT INTO wohnort (id,wohnort) VALUES (378, 'Altlandsberg' );
INSERT INTO wohnort (id,wohnort) VALUES (379, 'Heinsberg' );
INSERT INTO wohnort (id,wohnort) VALUES (380, 'Waldshut-Tiengen' );
INSERT INTO wohnort (id,wohnort) VALUES (381, 'Breitungen/Werra' );
INSERT INTO wohnort (id,wohnort) VALUES (382, 'Schifferstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (383, 'Blankenstein' );
INSERT INTO wohnort (id,wohnort) VALUES (384, 'Anklam' );
INSERT INTO wohnort (id,wohnort) VALUES (385, 'Moers' );
INSERT INTO wohnort (id,wohnort) VALUES (386, 'Plüderhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (387, 'Cloppenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (388, 'Bönen' );
INSERT INTO wohnort (id,wohnort) VALUES (389, 'Blieskastel' );
INSERT INTO wohnort (id,wohnort) VALUES (390, 'Weissach' );
INSERT INTO wohnort (id,wohnort) VALUES (391, 'Rottenburg a.d.Laaber' );
INSERT INTO wohnort (id,wohnort) VALUES (392, 'Netphen' );
INSERT INTO wohnort (id,wohnort) VALUES (393, 'Prenzlau' );
INSERT INTO wohnort (id,wohnort) VALUES (394, 'Spreenhagen' );
INSERT INTO wohnort (id,wohnort) VALUES (395, 'Giesen' );
INSERT INTO wohnort (id,wohnort) VALUES (396, 'Bad Boll' );
INSERT INTO wohnort (id,wohnort) VALUES (397, 'Schramberg' );
INSERT INTO wohnort (id,wohnort) VALUES (398, 'Großschirma' );
INSERT INTO wohnort (id,wohnort) VALUES (399, 'Hamburg' );
INSERT INTO wohnort (id,wohnort) VALUES (400, 'Traunreut' );
INSERT INTO wohnort (id,wohnort) VALUES (401, 'Schöntal' );
INSERT INTO wohnort (id,wohnort) VALUES (402, 'Ebelsbach' );
INSERT INTO wohnort (id,wohnort) VALUES (403, 'Kretzschau' );
INSERT INTO wohnort (id,wohnort) VALUES (404, 'Oberkrämer' );
INSERT INTO wohnort (id,wohnort) VALUES (405, 'Stein-Wingert' );
INSERT INTO wohnort (id,wohnort) VALUES (406, 'Gundelsheim' );
INSERT INTO wohnort (id,wohnort) VALUES (407, 'Landau in der Pfalz' );
INSERT INTO wohnort (id,wohnort) VALUES (408, 'Lauterbach (Hessen)' );
INSERT INTO wohnort (id,wohnort) VALUES (409, 'Schleusingen' );
INSERT INTO wohnort (id,wohnort) VALUES (410, 'Markersdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (411, 'Lichtenfels' );
INSERT INTO wohnort (id,wohnort) VALUES (412, 'Großostheim' );
INSERT INTO wohnort (id,wohnort) VALUES (413, 'Zetel' );
INSERT INTO wohnort (id,wohnort) VALUES (414, 'Geilenkirchen' );
INSERT INTO wohnort (id,wohnort) VALUES (415, 'Dattenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (416, 'Schwanewede' );
INSERT INTO wohnort (id,wohnort) VALUES (417, 'Steimbke' );
INSERT INTO wohnort (id,wohnort) VALUES (418, 'Frankenblick' );
INSERT INTO wohnort (id,wohnort) VALUES (419, 'Gerlingen' );
INSERT INTO wohnort (id,wohnort) VALUES (420, 'Spremberg' );
INSERT INTO wohnort (id,wohnort) VALUES (421, 'Garmisch-Partenkirchen' );
INSERT INTO wohnort (id,wohnort) VALUES (422, 'Schauerberg' );
INSERT INTO wohnort (id,wohnort) VALUES (423, 'Zorneding' );
INSERT INTO wohnort (id,wohnort) VALUES (424, 'Gelsenkirchen' );
INSERT INTO wohnort (id,wohnort) VALUES (425, 'Obertrubach' );
INSERT INTO wohnort (id,wohnort) VALUES (426, 'Vaterstetten' );
INSERT INTO wohnort (id,wohnort) VALUES (427, 'Burgwedel' );
INSERT INTO wohnort (id,wohnort) VALUES (428, 'Kirkel' );
INSERT INTO wohnort (id,wohnort) VALUES (429, 'Wurmlingen' );
INSERT INTO wohnort (id,wohnort) VALUES (430, 'Lübeck' );
INSERT INTO wohnort (id,wohnort) VALUES (431, 'Ulm' );
INSERT INTO wohnort (id,wohnort) VALUES (432, 'Riedstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (433, 'Langweid a.Lech' );
INSERT INTO wohnort (id,wohnort) VALUES (434, 'Michelstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (435, 'Coburg' );
INSERT INTO wohnort (id,wohnort) VALUES (436, 'Raisting' );
INSERT INTO wohnort (id,wohnort) VALUES (437, 'Leingarten' );
INSERT INTO wohnort (id,wohnort) VALUES (438, 'Ketzin/Havel' );
INSERT INTO wohnort (id,wohnort) VALUES (439, 'Augsburg' );
INSERT INTO wohnort (id,wohnort) VALUES (440, 'Coppenbrügge' );
INSERT INTO wohnort (id,wohnort) VALUES (441, 'Lienen' );
INSERT INTO wohnort (id,wohnort) VALUES (442, 'Brüggen' );
INSERT INTO wohnort (id,wohnort) VALUES (443, 'Tyrlaching' );
INSERT INTO wohnort (id,wohnort) VALUES (444, 'Neubeuern' );
INSERT INTO wohnort (id,wohnort) VALUES (445, 'Willich' );
INSERT INTO wohnort (id,wohnort) VALUES (446, 'Zilshausen' );
INSERT INTO wohnort (id,wohnort) VALUES (447, 'Albbruck' );
INSERT INTO wohnort (id,wohnort) VALUES (448, 'Leer (Ostfriesland)' );
INSERT INTO wohnort (id,wohnort) VALUES (449, 'Rodgau' );
INSERT INTO wohnort (id,wohnort) VALUES (450, 'Pegnitz' );
INSERT INTO wohnort (id,wohnort) VALUES (451, 'Regensburg' );
INSERT INTO wohnort (id,wohnort) VALUES (452, 'Gernrode' );
INSERT INTO wohnort (id,wohnort) VALUES (453, 'Sulzberg' );
INSERT INTO wohnort (id,wohnort) VALUES (454, 'Oppenheim' );
INSERT INTO wohnort (id,wohnort) VALUES (455, 'Briesen (Mark)' );
INSERT INTO wohnort (id,wohnort) VALUES (456, 'Dachau' );
INSERT INTO wohnort (id,wohnort) VALUES (457, 'Flörsbachtal' );
INSERT INTO wohnort (id,wohnort) VALUES (458, 'Großrückerswalde' );
INSERT INTO wohnort (id,wohnort) VALUES (459, 'Fronreute' );
INSERT INTO wohnort (id,wohnort) VALUES (460, 'Kamen' );
INSERT INTO wohnort (id,wohnort) VALUES (461, 'Byhleguhre-Byhlen' );
INSERT INTO wohnort (id,wohnort) VALUES (462, 'Weingarten' );
INSERT INTO wohnort (id,wohnort) VALUES (463, 'Bergisch Gladbach' );
INSERT INTO wohnort (id,wohnort) VALUES (464, 'Haltern am See' );
INSERT INTO wohnort (id,wohnort) VALUES (465, 'Katzenelnbogen' );
INSERT INTO wohnort (id,wohnort) VALUES (466, 'Illingen' );
INSERT INTO wohnort (id,wohnort) VALUES (467, 'Eisleben' );
INSERT INTO wohnort (id,wohnort) VALUES (468, 'Radevormwald' );
INSERT INTO wohnort (id,wohnort) VALUES (469, 'Karlum' );
INSERT INTO wohnort (id,wohnort) VALUES (470, 'Bad Honnef' );
INSERT INTO wohnort (id,wohnort) VALUES (471, 'Koblenz' );
INSERT INTO wohnort (id,wohnort) VALUES (472, 'Groß Teetzleben' );
INSERT INTO wohnort (id,wohnort) VALUES (473, 'Wanderup' );
INSERT INTO wohnort (id,wohnort) VALUES (474, 'Ummendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (475, 'Obertshausen' );
INSERT INTO wohnort (id,wohnort) VALUES (476, 'Königstein im Taunus' );
INSERT INTO wohnort (id,wohnort) VALUES (477, 'Mannheim' );
INSERT INTO wohnort (id,wohnort) VALUES (478, 'Michendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (479, 'Lübtheen' );
INSERT INTO wohnort (id,wohnort) VALUES (480, 'Gablenz' );
INSERT INTO wohnort (id,wohnort) VALUES (481, 'Braubach' );
INSERT INTO wohnort (id,wohnort) VALUES (482, 'Celle' );
INSERT INTO wohnort (id,wohnort) VALUES (483, 'Delbrück' );
INSERT INTO wohnort (id,wohnort) VALUES (484, 'Rehburg-Loccum' );
INSERT INTO wohnort (id,wohnort) VALUES (485, 'Ahaus' );
INSERT INTO wohnort (id,wohnort) VALUES (486, 'Wriedel' );
INSERT INTO wohnort (id,wohnort) VALUES (487, 'Giekau' );
INSERT INTO wohnort (id,wohnort) VALUES (488, 'Erlangen' );
INSERT INTO wohnort (id,wohnort) VALUES (489, 'Altena' );
INSERT INTO wohnort (id,wohnort) VALUES (490, 'Meiningen' );
INSERT INTO wohnort (id,wohnort) VALUES (491, 'Trier' );
INSERT INTO wohnort (id,wohnort) VALUES (492, 'Baden-Baden' );
INSERT INTO wohnort (id,wohnort) VALUES (493, 'Stendal' );
INSERT INTO wohnort (id,wohnort) VALUES (494, 'Viersen' );
INSERT INTO wohnort (id,wohnort) VALUES (495, 'Ringe' );
INSERT INTO wohnort (id,wohnort) VALUES (496, 'Naumburg (Saale)' );
INSERT INTO wohnort (id,wohnort) VALUES (497, 'Dietzenbach' );
INSERT INTO wohnort (id,wohnort) VALUES (498, 'Harsewinkel' );
INSERT INTO wohnort (id,wohnort) VALUES (499, 'Passade' );
INSERT INTO wohnort (id,wohnort) VALUES (500, 'Erlensee' );
INSERT INTO wohnort (id,wohnort) VALUES (501, 'Leichlingen (Rheinland)' );
INSERT INTO wohnort (id,wohnort) VALUES (502, 'Viechtach' );
INSERT INTO wohnort (id,wohnort) VALUES (503, 'Gemünden a.Main' );
INSERT INTO wohnort (id,wohnort) VALUES (504, 'Balingen' );
INSERT INTO wohnort (id,wohnort) VALUES (505, 'Gütersloh' );
INSERT INTO wohnort (id,wohnort) VALUES (506, 'Güsten' );
INSERT INTO wohnort (id,wohnort) VALUES (507, 'Rehlingen-Siersburg' );
INSERT INTO wohnort (id,wohnort) VALUES (508, 'Frechen' );
INSERT INTO wohnort (id,wohnort) VALUES (509, 'Stralsund' );
INSERT INTO wohnort (id,wohnort) VALUES (510, 'Köthen (Anhalt)' );
INSERT INTO wohnort (id,wohnort) VALUES (511, 'Mörlenbach' );
INSERT INTO wohnort (id,wohnort) VALUES (512, 'Brandenburg an der Havel' );
INSERT INTO wohnort (id,wohnort) VALUES (513, 'Schweinfurt' );
INSERT INTO wohnort (id,wohnort) VALUES (514, 'Bad Münder am Deister' );
INSERT INTO wohnort (id,wohnort) VALUES (515, 'Weil der Stadt' );
INSERT INTO wohnort (id,wohnort) VALUES (516, 'Litzendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (517, 'Königsbrunn' );
INSERT INTO wohnort (id,wohnort) VALUES (518, 'Hofheim am Taunus' );
INSERT INTO wohnort (id,wohnort) VALUES (519, 'Büsingen am Hochrhein' );
INSERT INTO wohnort (id,wohnort) VALUES (520, 'Neukirchen-Vluyn' );
INSERT INTO wohnort (id,wohnort) VALUES (521, 'Kusterdingen' );
INSERT INTO wohnort (id,wohnort) VALUES (522, 'Dickel' );
INSERT INTO wohnort (id,wohnort) VALUES (523, 'Saalfeld/Saale' );
INSERT INTO wohnort (id,wohnort) VALUES (524, 'Wetzlar' );
INSERT INTO wohnort (id,wohnort) VALUES (525, 'Ravensburg' );
INSERT INTO wohnort (id,wohnort) VALUES (526, 'Stuttgart' );
INSERT INTO wohnort (id,wohnort) VALUES (527, 'Bad Nauheim' );
INSERT INTO wohnort (id,wohnort) VALUES (528, 'Büdingen' );
INSERT INTO wohnort (id,wohnort) VALUES (529, 'Niederwambach' );
INSERT INTO wohnort (id,wohnort) VALUES (530, 'Mühlhausen/Thüringen' );
INSERT INTO wohnort (id,wohnort) VALUES (531, 'Goldberg' );
INSERT INTO wohnort (id,wohnort) VALUES (532, 'Limburg a.d. Lahn' );
INSERT INTO wohnort (id,wohnort) VALUES (533, 'Breisach am Rhein' );
INSERT INTO wohnort (id,wohnort) VALUES (534, 'Tetenhusen' );
INSERT INTO wohnort (id,wohnort) VALUES (535, 'Osternienburger Land' );
INSERT INTO wohnort (id,wohnort) VALUES (536, 'Sankt Michaelisdonn' );
INSERT INTO wohnort (id,wohnort) VALUES (537, 'Bünde' );
INSERT INTO wohnort (id,wohnort) VALUES (538, 'Siegen' );
INSERT INTO wohnort (id,wohnort) VALUES (539, 'Waldstetten' );
INSERT INTO wohnort (id,wohnort) VALUES (540, 'Northeim' );
INSERT INTO wohnort (id,wohnort) VALUES (541, 'Burgdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (542, 'Hannover' );
INSERT INTO wohnort (id,wohnort) VALUES (543, 'Imsbach' );
INSERT INTO wohnort (id,wohnort) VALUES (544, 'Pellingen' );
INSERT INTO wohnort (id,wohnort) VALUES (545, 'Harsefeld' );
INSERT INTO wohnort (id,wohnort) VALUES (546, 'Weimar' );
INSERT INTO wohnort (id,wohnort) VALUES (547, 'Ampfing' );
INSERT INTO wohnort (id,wohnort) VALUES (548, 'Falkensee' );
INSERT INTO wohnort (id,wohnort) VALUES (549, 'Wiesenburg/Mark' );
INSERT INTO wohnort (id,wohnort) VALUES (550, 'Steinau an der Straße' );
INSERT INTO wohnort (id,wohnort) VALUES (551, 'Palling' );
INSERT INTO wohnort (id,wohnort) VALUES (552, 'Bad Vilbel' );
INSERT INTO wohnort (id,wohnort) VALUES (553, 'Pfinztal' );
INSERT INTO wohnort (id,wohnort) VALUES (554, 'Scheuring' );
INSERT INTO wohnort (id,wohnort) VALUES (555, 'Grönwohld' );
INSERT INTO wohnort (id,wohnort) VALUES (556, 'Velbert' );
INSERT INTO wohnort (id,wohnort) VALUES (557, 'Weißkeißel' );
INSERT INTO wohnort (id,wohnort) VALUES (558, 'Sonnenstein' );
INSERT INTO wohnort (id,wohnort) VALUES (559, 'Mihla' );
INSERT INTO wohnort (id,wohnort) VALUES (560, 'Reutlingen' );
INSERT INTO wohnort (id,wohnort) VALUES (561, 'Großenseebach' );
INSERT INTO wohnort (id,wohnort) VALUES (562, 'Rotenburg a. d. Fulda' );
INSERT INTO wohnort (id,wohnort) VALUES (563, 'Bietigheim-Bissingen' );
INSERT INTO wohnort (id,wohnort) VALUES (564, 'Erpel' );
INSERT INTO wohnort (id,wohnort) VALUES (565, 'Bremerhaven' );
INSERT INTO wohnort (id,wohnort) VALUES (566, 'Stuhr' );
INSERT INTO wohnort (id,wohnort) VALUES (567, 'Bad Sassendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (568, 'Wernigerode' );
INSERT INTO wohnort (id,wohnort) VALUES (569, 'Waren (Müritz)' );
INSERT INTO wohnort (id,wohnort) VALUES (570, 'Barleben' );
INSERT INTO wohnort (id,wohnort) VALUES (571, 'Dägeling' );
INSERT INTO wohnort (id,wohnort) VALUES (572, 'Oberaudorf' );
INSERT INTO wohnort (id,wohnort) VALUES (573, 'Emden' );
INSERT INTO wohnort (id,wohnort) VALUES (574, 'Trebur' );
INSERT INTO wohnort (id,wohnort) VALUES (575, 'Berg' );
INSERT INTO wohnort (id,wohnort) VALUES (576, 'Zwickau' );
INSERT INTO wohnort (id,wohnort) VALUES (577, 'Lünen' );
INSERT INTO wohnort (id,wohnort) VALUES (578, 'Lachendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (579, 'Neu-Ulm' );
INSERT INTO wohnort (id,wohnort) VALUES (580, 'Emstek' );
INSERT INTO wohnort (id,wohnort) VALUES (581, 'Suhl' );
INSERT INTO wohnort (id,wohnort) VALUES (582, 'Reichenau' );
INSERT INTO wohnort (id,wohnort) VALUES (583, 'Korbach' );
INSERT INTO wohnort (id,wohnort) VALUES (584, 'Belm' );
INSERT INTO wohnort (id,wohnort) VALUES (585, 'Goldbach' );
INSERT INTO wohnort (id,wohnort) VALUES (586, 'Tangermünde' );
INSERT INTO wohnort (id,wohnort) VALUES (587, 'Schwäbisch Hall' );
INSERT INTO wohnort (id,wohnort) VALUES (588, 'Enger' );
INSERT INTO wohnort (id,wohnort) VALUES (589, 'Frankenhain' );
INSERT INTO wohnort (id,wohnort) VALUES (590, 'Kornwestheim' );
INSERT INTO wohnort (id,wohnort) VALUES (591, 'Morbach' );
INSERT INTO wohnort (id,wohnort) VALUES (592, 'Wesseling' );
INSERT INTO wohnort (id,wohnort) VALUES (593, 'Soyen' );
INSERT INTO wohnort (id,wohnort) VALUES (594, 'Mülsen' );
INSERT INTO wohnort (id,wohnort) VALUES (595, 'Leinfelden-Echterdingen' );
INSERT INTO wohnort (id,wohnort) VALUES (596, 'Hameln' );
INSERT INTO wohnort (id,wohnort) VALUES (597, 'Brilon' );
INSERT INTO wohnort (id,wohnort) VALUES (598, 'Dornstetten' );
INSERT INTO wohnort (id,wohnort) VALUES (599, 'Lehmkuhlen' );
INSERT INTO wohnort (id,wohnort) VALUES (600, 'Neubulach' );
INSERT INTO wohnort (id,wohnort) VALUES (601, 'Radolfzell am Bodensee' );
INSERT INTO wohnort (id,wohnort) VALUES (602, 'Wackersdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (603, 'Lübben (Spreewald)' );
INSERT INTO wohnort (id,wohnort) VALUES (604, 'St. Leon-Rot' );
INSERT INTO wohnort (id,wohnort) VALUES (605, 'Niebüll' );
INSERT INTO wohnort (id,wohnort) VALUES (606, 'Ortenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (607, 'Weil am Rhein' );
INSERT INTO wohnort (id,wohnort) VALUES (608, 'Bedburg' );
INSERT INTO wohnort (id,wohnort) VALUES (609, 'Mallersdorf-Pfaffenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (610, 'Mörfelden-Walldorf' );
INSERT INTO wohnort (id,wohnort) VALUES (611, 'Aalen' );
INSERT INTO wohnort (id,wohnort) VALUES (612, 'Laupheim' );
INSERT INTO wohnort (id,wohnort) VALUES (613, 'Leipzig' );
INSERT INTO wohnort (id,wohnort) VALUES (614, 'Neustadt (Hessen)' );
INSERT INTO wohnort (id,wohnort) VALUES (615, 'Freital' );
INSERT INTO wohnort (id,wohnort) VALUES (616, 'Bensheim' );
INSERT INTO wohnort (id,wohnort) VALUES (617, 'Gersthofen' );
INSERT INTO wohnort (id,wohnort) VALUES (618, 'Gerbstedt' );
INSERT INTO wohnort (id,wohnort) VALUES (619, 'Wildeck' );
INSERT INTO wohnort (id,wohnort) VALUES (620, 'Dresden' );
INSERT INTO wohnort (id,wohnort) VALUES (621, 'Cuxhaven' );
INSERT INTO wohnort (id,wohnort) VALUES (622, 'Langballig' );
INSERT INTO wohnort (id,wohnort) VALUES (623, 'Roding' );
INSERT INTO wohnort (id,wohnort) VALUES (624, 'Oberkochen' );
INSERT INTO wohnort (id,wohnort) VALUES (625, 'Heidenheim an der Brenz' );
INSERT INTO wohnort (id,wohnort) VALUES (626, 'Brachtendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (627, 'Schmidmühlen' );
INSERT INTO wohnort (id,wohnort) VALUES (628, 'Werdau' );
INSERT INTO wohnort (id,wohnort) VALUES (629, 'Bad Liebenwerda' );
INSERT INTO wohnort (id,wohnort) VALUES (630, 'Salzwedel' );
INSERT INTO wohnort (id,wohnort) VALUES (631, 'Stade' );
INSERT INTO wohnort (id,wohnort) VALUES (632, 'Kaulsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (633, 'Stadtbergen' );
INSERT INTO wohnort (id,wohnort) VALUES (634, 'Waldthurn' );
INSERT INTO wohnort (id,wohnort) VALUES (635, 'Biesenthal' );
INSERT INTO wohnort (id,wohnort) VALUES (636, 'Nierstein' );
INSERT INTO wohnort (id,wohnort) VALUES (637, 'Wetter (Ruhr)' );
INSERT INTO wohnort (id,wohnort) VALUES (638, 'Zörbig' );
INSERT INTO wohnort (id,wohnort) VALUES (639, 'Osthofen' );
INSERT INTO wohnort (id,wohnort) VALUES (640, 'Bramsche' );
INSERT INTO wohnort (id,wohnort) VALUES (641, 'Prerow' );
INSERT INTO wohnort (id,wohnort) VALUES (642, 'Herten' );
INSERT INTO wohnort (id,wohnort) VALUES (643, 'Hamm' );
INSERT INTO wohnort (id,wohnort) VALUES (644, 'Lemberg' );
INSERT INTO wohnort (id,wohnort) VALUES (645, 'Friedrichshafen' );
INSERT INTO wohnort (id,wohnort) VALUES (646, 'Butzbach' );
INSERT INTO wohnort (id,wohnort) VALUES (647, 'Klipphausen' );
INSERT INTO wohnort (id,wohnort) VALUES (648, 'Eichenau' );
INSERT INTO wohnort (id,wohnort) VALUES (649, 'Rödermark' );
INSERT INTO wohnort (id,wohnort) VALUES (650, 'Amöneburg' );
INSERT INTO wohnort (id,wohnort) VALUES (651, 'Dülmen' );
INSERT INTO wohnort (id,wohnort) VALUES (652, 'Wolfenbüttel' );
INSERT INTO wohnort (id,wohnort) VALUES (653, 'Markt Einersheim' );
INSERT INTO wohnort (id,wohnort) VALUES (654, 'Rüsselsheim am Main' );
INSERT INTO wohnort (id,wohnort) VALUES (655, 'Eppingen' );
INSERT INTO wohnort (id,wohnort) VALUES (656, 'Brandscheid' );
INSERT INTO wohnort (id,wohnort) VALUES (657, 'Weißenhorn' );
INSERT INTO wohnort (id,wohnort) VALUES (658, 'Herdecke' );
INSERT INTO wohnort (id,wohnort) VALUES (659, 'Winsen (Luhe)' );
INSERT INTO wohnort (id,wohnort) VALUES (660, 'Amberg' );
INSERT INTO wohnort (id,wohnort) VALUES (661, 'Velden' );
INSERT INTO wohnort (id,wohnort) VALUES (662, 'Bergkamen' );
INSERT INTO wohnort (id,wohnort) VALUES (663, 'Hebertsfelden' );
INSERT INTO wohnort (id,wohnort) VALUES (664, 'Ratzeburg' );
INSERT INTO wohnort (id,wohnort) VALUES (665, 'Karlsruhe' );
INSERT INTO wohnort (id,wohnort) VALUES (666, 'Rastatt' );
INSERT INTO wohnort (id,wohnort) VALUES (667, 'Melle' );
INSERT INTO wohnort (id,wohnort) VALUES (668, 'Traben-Trarbach' );
INSERT INTO wohnort (id,wohnort) VALUES (669, 'Kempen' );
INSERT INTO wohnort (id,wohnort) VALUES (670, 'Arnstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (671, 'Freudenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (672, 'Attendorn' );
INSERT INTO wohnort (id,wohnort) VALUES (673, 'Untersteinach' );
INSERT INTO wohnort (id,wohnort) VALUES (674, 'Kleinmachnow' );
INSERT INTO wohnort (id,wohnort) VALUES (675, 'Hohenbrunn' );
INSERT INTO wohnort (id,wohnort) VALUES (676, 'Hünstetten' );
INSERT INTO wohnort (id,wohnort) VALUES (677, 'Alerheim' );
INSERT INTO wohnort (id,wohnort) VALUES (678, 'Delmenhorst' );
INSERT INTO wohnort (id,wohnort) VALUES (679, 'Nersingen' );
INSERT INTO wohnort (id,wohnort) VALUES (680, 'Saarlouis' );
INSERT INTO wohnort (id,wohnort) VALUES (681, 'Bocholt' );
INSERT INTO wohnort (id,wohnort) VALUES (682, 'Bielefeld' );
INSERT INTO wohnort (id,wohnort) VALUES (683, 'Sassnitz' );
INSERT INTO wohnort (id,wohnort) VALUES (684, 'Petersaurach' );
INSERT INTO wohnort (id,wohnort) VALUES (685, 'Gröbenzell' );
INSERT INTO wohnort (id,wohnort) VALUES (686, 'Lauffen am Neckar' );
INSERT INTO wohnort (id,wohnort) VALUES (687, 'Hoisdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (688, 'Groß Kreutz (Havel)' );
INSERT INTO wohnort (id,wohnort) VALUES (689, 'Nobitz' );
INSERT INTO wohnort (id,wohnort) VALUES (690, 'Kaiserslautern' );
INSERT INTO wohnort (id,wohnort) VALUES (691, 'Keltern' );
INSERT INTO wohnort (id,wohnort) VALUES (692, 'Parchim' );
INSERT INTO wohnort (id,wohnort) VALUES (693, 'Tholey' );
INSERT INTO wohnort (id,wohnort) VALUES (694, 'Marl' );
INSERT INTO wohnort (id,wohnort) VALUES (695, 'Heinersreuth' );
INSERT INTO wohnort (id,wohnort) VALUES (696, 'Döbern' );
INSERT INTO wohnort (id,wohnort) VALUES (697, 'Mömbris' );
INSERT INTO wohnort (id,wohnort) VALUES (698, 'Weste' );
INSERT INTO wohnort (id,wohnort) VALUES (699, 'Bernau bei Berlin' );
INSERT INTO wohnort (id,wohnort) VALUES (700, 'Gießen' );
INSERT INTO wohnort (id,wohnort) VALUES (701, 'Garbsen' );
INSERT INTO wohnort (id,wohnort) VALUES (702, 'Fellbach' );
INSERT INTO wohnort (id,wohnort) VALUES (703, 'Gera' );
INSERT INTO wohnort (id,wohnort) VALUES (704, 'Nienburg (Weser)' );
INSERT INTO wohnort (id,wohnort) VALUES (705, 'Tübingen' );
INSERT INTO wohnort (id,wohnort) VALUES (706, 'Wahlstedt' );
INSERT INTO wohnort (id,wohnort) VALUES (707, 'Bad Wünnenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (708, 'Berlin' );
INSERT INTO wohnort (id,wohnort) VALUES (709, 'Beerfelden' );
INSERT INTO wohnort (id,wohnort) VALUES (710, 'Marienmünster' );
INSERT INTO wohnort (id,wohnort) VALUES (711, 'Bernsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (712, 'Panketal' );
INSERT INTO wohnort (id,wohnort) VALUES (713, 'Schwarzenbruck' );
INSERT INTO wohnort (id,wohnort) VALUES (714, 'Großefehn' );
INSERT INTO wohnort (id,wohnort) VALUES (715, 'Überlingen' );
INSERT INTO wohnort (id,wohnort) VALUES (716, 'Böhmenkirch' );
INSERT INTO wohnort (id,wohnort) VALUES (717, 'Wuppertal' );
INSERT INTO wohnort (id,wohnort) VALUES (718, 'Eckernförde' );
INSERT INTO wohnort (id,wohnort) VALUES (719, 'Köthel' );
INSERT INTO wohnort (id,wohnort) VALUES (720, 'Kiel' );
INSERT INTO wohnort (id,wohnort) VALUES (721, 'Wolnzach' );
INSERT INTO wohnort (id,wohnort) VALUES (722, 'Hohen Neuendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (723, 'Kempten (Allgäu)' );
INSERT INTO wohnort (id,wohnort) VALUES (724, 'Salzkotten' );
INSERT INTO wohnort (id,wohnort) VALUES (725, 'Wadern' );
INSERT INTO wohnort (id,wohnort) VALUES (726, 'Gehrden' );
INSERT INTO wohnort (id,wohnort) VALUES (727, 'Bad Driburg' );
INSERT INTO wohnort (id,wohnort) VALUES (728, 'Düsseldorf' );
INSERT INTO wohnort (id,wohnort) VALUES (729, 'Bad Zwischenahn' );
INSERT INTO wohnort (id,wohnort) VALUES (730, 'Dinslaken' );
INSERT INTO wohnort (id,wohnort) VALUES (731, 'Westoverledingen' );
INSERT INTO wohnort (id,wohnort) VALUES (732, 'Eich' );
INSERT INTO wohnort (id,wohnort) VALUES (733, 'Seelingstädt' );
INSERT INTO wohnort (id,wohnort) VALUES (734, 'Würzburg' );
INSERT INTO wohnort (id,wohnort) VALUES (735, 'Detmold' );
INSERT INTO wohnort (id,wohnort) VALUES (736, 'Marktoberdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (737, 'Kirchberg an der Jagst' );
INSERT INTO wohnort (id,wohnort) VALUES (738, 'Bellenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (739, 'Bismark (Altmark)' );
INSERT INTO wohnort (id,wohnort) VALUES (740, 'Neuhofen' );
INSERT INTO wohnort (id,wohnort) VALUES (741, 'Erbach' );
INSERT INTO wohnort (id,wohnort) VALUES (742, 'Freiberg' );
INSERT INTO wohnort (id,wohnort) VALUES (743, 'Bonn' );
INSERT INTO wohnort (id,wohnort) VALUES (744, 'Erfurt' );
INSERT INTO wohnort (id,wohnort) VALUES (745, 'Freiburg im Breisgau' );
INSERT INTO wohnort (id,wohnort) VALUES (746, 'Ribbesbüttel' );
INSERT INTO wohnort (id,wohnort) VALUES (747, 'Ingolstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (748, 'Illertissen' );
INSERT INTO wohnort (id,wohnort) VALUES (749, 'Neunkirchen' );
INSERT INTO wohnort (id,wohnort) VALUES (750, 'Saara' );
INSERT INTO wohnort (id,wohnort) VALUES (751, 'Kreuztal' );
INSERT INTO wohnort (id,wohnort) VALUES (752, 'Neuss' );
INSERT INTO wohnort (id,wohnort) VALUES (753, 'Betzdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (754, 'Weiden i.d.OPf.' );
INSERT INTO wohnort (id,wohnort) VALUES (755, 'Waidhaus' );
INSERT INTO wohnort (id,wohnort) VALUES (756, 'Aying' );
INSERT INTO wohnort (id,wohnort) VALUES (757, 'Mülheim an der Ruhr' );
INSERT INTO wohnort (id,wohnort) VALUES (758, 'Andernach' );
INSERT INTO wohnort (id,wohnort) VALUES (759, 'Großröhrsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (760, 'Kamp-Lintfort' );
INSERT INTO wohnort (id,wohnort) VALUES (761, 'Rülzheim' );
INSERT INTO wohnort (id,wohnort) VALUES (762, 'Gundheim' );
INSERT INTO wohnort (id,wohnort) VALUES (763, 'Böhl-Iggelheim' );
INSERT INTO wohnort (id,wohnort) VALUES (764, 'Alfeld (Leine)' );
INSERT INTO wohnort (id,wohnort) VALUES (765, 'Papenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (766, 'Torgau' );
INSERT INTO wohnort (id,wohnort) VALUES (767, 'Neustadt a.d.Waldnaab' );
INSERT INTO wohnort (id,wohnort) VALUES (768, 'Dörentrup' );
INSERT INTO wohnort (id,wohnort) VALUES (769, 'Malchow' );
INSERT INTO wohnort (id,wohnort) VALUES (770, 'Hechingen' );
INSERT INTO wohnort (id,wohnort) VALUES (771, 'Münster' );
INSERT INTO wohnort (id,wohnort) VALUES (772, 'Möhrendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (773, 'Vetschau/Spreewald' );
INSERT INTO wohnort (id,wohnort) VALUES (774, 'Pulheim' );
INSERT INTO wohnort (id,wohnort) VALUES (775, 'Ilmenau' );
INSERT INTO wohnort (id,wohnort) VALUES (776, 'Immenstaad am Bodensee' );
INSERT INTO wohnort (id,wohnort) VALUES (777, 'Ahrensburg' );
INSERT INTO wohnort (id,wohnort) VALUES (778, 'Beeskow' );
INSERT INTO wohnort (id,wohnort) VALUES (779, 'Holzkirchen' );
INSERT INTO wohnort (id,wohnort) VALUES (780, 'Templin' );
INSERT INTO wohnort (id,wohnort) VALUES (781, 'Lüdenscheid' );
INSERT INTO wohnort (id,wohnort) VALUES (782, 'Colditz' );
INSERT INTO wohnort (id,wohnort) VALUES (783, 'Everswinkel' );
INSERT INTO wohnort (id,wohnort) VALUES (784, 'Landsberg am Lech' );
INSERT INTO wohnort (id,wohnort) VALUES (785, 'Rauenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (786, 'Krefeld' );
INSERT INTO wohnort (id,wohnort) VALUES (787, 'Bad Kreuznach' );
INSERT INTO wohnort (id,wohnort) VALUES (788, 'Bad Reichenhall' );
INSERT INTO wohnort (id,wohnort) VALUES (789, 'Lindenau' );
INSERT INTO wohnort (id,wohnort) VALUES (790, 'Kaufungen' );
INSERT INTO wohnort (id,wohnort) VALUES (791, 'Ganderkesee' );
INSERT INTO wohnort (id,wohnort) VALUES (792, 'Angelburg' );
INSERT INTO wohnort (id,wohnort) VALUES (793, 'Braunschweig' );
INSERT INTO wohnort (id,wohnort) VALUES (794, 'Essenbach' );
INSERT INTO wohnort (id,wohnort) VALUES (795, 'Kleinostheim' );
INSERT INTO wohnort (id,wohnort) VALUES (796, 'Wiesloch' );
INSERT INTO wohnort (id,wohnort) VALUES (797, 'Zapel' );
INSERT INTO wohnort (id,wohnort) VALUES (798, 'Icking' );
INSERT INTO wohnort (id,wohnort) VALUES (799, 'Kirchtimke' );
INSERT INTO wohnort (id,wohnort) VALUES (800, 'Schönbach' );
INSERT INTO wohnort (id,wohnort) VALUES (801, 'Ludwigshafen am Rhein' );
INSERT INTO wohnort (id,wohnort) VALUES (802, 'Esslingen am Neckar' );
INSERT INTO wohnort (id,wohnort) VALUES (803, 'Riegelsberg' );
INSERT INTO wohnort (id,wohnort) VALUES (804, 'Planegg' );
INSERT INTO wohnort (id,wohnort) VALUES (805, 'Inning a.Holz' );
INSERT INTO wohnort (id,wohnort) VALUES (806, 'Sendenhorst' );
INSERT INTO wohnort (id,wohnort) VALUES (807, 'Goslar' );
INSERT INTO wohnort (id,wohnort) VALUES (808, 'Großenkneten' );
INSERT INTO wohnort (id,wohnort) VALUES (809, 'Ilsede' );
INSERT INTO wohnort (id,wohnort) VALUES (810, 'Ihlow' );
INSERT INTO wohnort (id,wohnort) VALUES (811, 'Waake' );
INSERT INTO wohnort (id,wohnort) VALUES (812, 'Esselbach' );
INSERT INTO wohnort (id,wohnort) VALUES (813, 'Mainz' );
INSERT INTO wohnort (id,wohnort) VALUES (814, 'Heilbronn' );
INSERT INTO wohnort (id,wohnort) VALUES (815, 'Neustadt am Rübenberge' );
INSERT INTO wohnort (id,wohnort) VALUES (816, 'Hesel' );
INSERT INTO wohnort (id,wohnort) VALUES (817, 'Ense' );
INSERT INTO wohnort (id,wohnort) VALUES (818, 'Hohenstein' );
INSERT INTO wohnort (id,wohnort) VALUES (819, 'Mönchhagen' );
INSERT INTO wohnort (id,wohnort) VALUES (820, 'Uhingen' );
INSERT INTO wohnort (id,wohnort) VALUES (821, 'Winnerath' );
INSERT INTO wohnort (id,wohnort) VALUES (822, 'Eschwege' );
INSERT INTO wohnort (id,wohnort) VALUES (823, 'Passau' );
INSERT INTO wohnort (id,wohnort) VALUES (824, 'Möckmühl' );
INSERT INTO wohnort (id,wohnort) VALUES (825, 'Seevetal' );
INSERT INTO wohnort (id,wohnort) VALUES (826, 'Dießen am Ammersee' );
INSERT INTO wohnort (id,wohnort) VALUES (827, 'Rechberghausen' );
INSERT INTO wohnort (id,wohnort) VALUES (828, 'Gerstetten' );
INSERT INTO wohnort (id,wohnort) VALUES (829, 'Achim' );
INSERT INTO wohnort (id,wohnort) VALUES (830, 'Wallersheim' );
INSERT INTO wohnort (id,wohnort) VALUES (831, 'Wiesbaden' );
INSERT INTO wohnort (id,wohnort) VALUES (832, 'Idar-Oberstein' );
INSERT INTO wohnort (id,wohnort) VALUES (833, 'Eisenhüttenstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (834, 'Zeitz' );
INSERT INTO wohnort (id,wohnort) VALUES (835, 'Jockgrim' );
INSERT INTO wohnort (id,wohnort) VALUES (836, 'Lensahn' );
INSERT INTO wohnort (id,wohnort) VALUES (837, 'Dorsten' );
INSERT INTO wohnort (id,wohnort) VALUES (838, 'Bonndorf im Schwarzwald' );
INSERT INTO wohnort (id,wohnort) VALUES (839, 'Lippetal' );
INSERT INTO wohnort (id,wohnort) VALUES (840, 'Lauta' );
INSERT INTO wohnort (id,wohnort) VALUES (841, 'Voerde (Niederrhein)' );
INSERT INTO wohnort (id,wohnort) VALUES (842, 'Billigheim' );
INSERT INTO wohnort (id,wohnort) VALUES (843, 'Südheide' );
INSERT INTO wohnort (id,wohnort) VALUES (844, 'Schwabbruck' );
INSERT INTO wohnort (id,wohnort) VALUES (845, 'Geeste' );
INSERT INTO wohnort (id,wohnort) VALUES (846, 'Ettlingen' );
INSERT INTO wohnort (id,wohnort) VALUES (847, 'Ilmtal-Weinstraße' );
INSERT INTO wohnort (id,wohnort) VALUES (848, 'Benshausen' );
INSERT INTO wohnort (id,wohnort) VALUES (849, 'Regenstauf' );
INSERT INTO wohnort (id,wohnort) VALUES (850, 'Hilden' );
INSERT INTO wohnort (id,wohnort) VALUES (851, 'Lengerich' );
INSERT INTO wohnort (id,wohnort) VALUES (852, 'Rosenheim' );
INSERT INTO wohnort (id,wohnort) VALUES (853, 'Strullendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (854, 'Königheim' );
INSERT INTO wohnort (id,wohnort) VALUES (855, 'Stutensee' );
INSERT INTO wohnort (id,wohnort) VALUES (856, 'Eislingen/Fils' );
INSERT INTO wohnort (id,wohnort) VALUES (857, 'Großheide' );
INSERT INTO wohnort (id,wohnort) VALUES (858, 'Villingen-Schwenningen' );
INSERT INTO wohnort (id,wohnort) VALUES (859, 'Teisnach' );
INSERT INTO wohnort (id,wohnort) VALUES (860, 'Mitterfels' );
INSERT INTO wohnort (id,wohnort) VALUES (861, 'Bornheim' );
INSERT INTO wohnort (id,wohnort) VALUES (862, 'March' );
INSERT INTO wohnort (id,wohnort) VALUES (863, 'Marklohe' );
INSERT INTO wohnort (id,wohnort) VALUES (864, 'Lübbecke' );
INSERT INTO wohnort (id,wohnort) VALUES (865, 'Pohlheim' );
INSERT INTO wohnort (id,wohnort) VALUES (866, 'Zerbst/Anhalt' );
INSERT INTO wohnort (id,wohnort) VALUES (867, 'Burgkirchen a.d.Alz' );
INSERT INTO wohnort (id,wohnort) VALUES (868, 'Neckargemünd' );
INSERT INTO wohnort (id,wohnort) VALUES (869, 'Rottach-Egern' );
INSERT INTO wohnort (id,wohnort) VALUES (870, 'Kirchheim unter Teck' );
INSERT INTO wohnort (id,wohnort) VALUES (871, 'Iserlohn' );
INSERT INTO wohnort (id,wohnort) VALUES (872, 'Wittenberge' );
INSERT INTO wohnort (id,wohnort) VALUES (873, 'Sehnde' );
INSERT INTO wohnort (id,wohnort) VALUES (874, 'Lohne (Oldenburg)' );
INSERT INTO wohnort (id,wohnort) VALUES (875, 'Dassel' );
INSERT INTO wohnort (id,wohnort) VALUES (876, 'Nordhorn' );
INSERT INTO wohnort (id,wohnort) VALUES (877, 'Dornburg-Camburg' );
INSERT INTO wohnort (id,wohnort) VALUES (878, 'Greifswald' );
INSERT INTO wohnort (id,wohnort) VALUES (879, 'Alsenz' );
INSERT INTO wohnort (id,wohnort) VALUES (880, 'Westerstede' );
INSERT INTO wohnort (id,wohnort) VALUES (881, 'Putzbrunn' );
INSERT INTO wohnort (id,wohnort) VALUES (882, 'Petershagen' );
INSERT INTO wohnort (id,wohnort) VALUES (883, 'Oelde' );
INSERT INTO wohnort (id,wohnort) VALUES (884, 'Pruchten' );
INSERT INTO wohnort (id,wohnort) VALUES (885, 'Neumarkt i.d.OPf.' );
INSERT INTO wohnort (id,wohnort) VALUES (886, 'Gudensberg' );
INSERT INTO wohnort (id,wohnort) VALUES (887, 'Wedemark' );
INSERT INTO wohnort (id,wohnort) VALUES (888, 'Weilerswist' );
INSERT INTO wohnort (id,wohnort) VALUES (889, 'Meckenheim' );
INSERT INTO wohnort (id,wohnort) VALUES (890, 'Rammelsbach' );
INSERT INTO wohnort (id,wohnort) VALUES (891, 'Hückeswagen' );
INSERT INTO wohnort (id,wohnort) VALUES (892, 'Bad Aibling' );
INSERT INTO wohnort (id,wohnort) VALUES (893, 'Kitzingen' );
INSERT INTO wohnort (id,wohnort) VALUES (894, 'Kassel' );
INSERT INTO wohnort (id,wohnort) VALUES (895, 'Burgkunstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (896, 'Stolberg (Rhld.)' );
INSERT INTO wohnort (id,wohnort) VALUES (897, 'Königstein' );
INSERT INTO wohnort (id,wohnort) VALUES (898, 'Meißen' );
INSERT INTO wohnort (id,wohnort) VALUES (899, 'Öhringen' );
INSERT INTO wohnort (id,wohnort) VALUES (900, 'Breddin' );
INSERT INTO wohnort (id,wohnort) VALUES (901, 'Fulda' );
INSERT INTO wohnort (id,wohnort) VALUES (902, 'Berne' );
INSERT INTO wohnort (id,wohnort) VALUES (903, 'Sangerhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (904, 'Brigachtal' );
INSERT INTO wohnort (id,wohnort) VALUES (905, 'Lauchringen' );
INSERT INTO wohnort (id,wohnort) VALUES (906, 'Olfen' );
INSERT INTO wohnort (id,wohnort) VALUES (907, 'Neuötting' );
INSERT INTO wohnort (id,wohnort) VALUES (908, 'Rednitzhembach' );
INSERT INTO wohnort (id,wohnort) VALUES (909, 'Dreieich' );
INSERT INTO wohnort (id,wohnort) VALUES (910, 'Niederdorfelden' );
INSERT INTO wohnort (id,wohnort) VALUES (911, 'Wolfsburg' );
INSERT INTO wohnort (id,wohnort) VALUES (912, 'Springe' );
INSERT INTO wohnort (id,wohnort) VALUES (913, 'Landshut' );
INSERT INTO wohnort (id,wohnort) VALUES (914, 'Stolzenau' );
INSERT INTO wohnort (id,wohnort) VALUES (915, 'Neuhof' );
INSERT INTO wohnort (id,wohnort) VALUES (916, 'Meitingen' );
INSERT INTO wohnort (id,wohnort) VALUES (917, 'Groß-Umstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (918, 'Engelskirchen' );
INSERT INTO wohnort (id,wohnort) VALUES (919, 'Limbach-Oberfrohna' );
INSERT INTO wohnort (id,wohnort) VALUES (920, 'Schonungen' );
INSERT INTO wohnort (id,wohnort) VALUES (921, 'Burkau' );
INSERT INTO wohnort (id,wohnort) VALUES (922, 'Milda' );
INSERT INTO wohnort (id,wohnort) VALUES (923, 'Dessau-Roßlau' );
INSERT INTO wohnort (id,wohnort) VALUES (924, 'Baiersbronn' );
INSERT INTO wohnort (id,wohnort) VALUES (925, 'Pforzheim' );
INSERT INTO wohnort (id,wohnort) VALUES (926, 'Zellingen' );
INSERT INTO wohnort (id,wohnort) VALUES (927, 'Kerpen' );
INSERT INTO wohnort (id,wohnort) VALUES (928, 'Bad Hersfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (929, 'Windeck' );
INSERT INTO wohnort (id,wohnort) VALUES (930, 'Burglengenfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (931, 'Tannheim' );
INSERT INTO wohnort (id,wohnort) VALUES (932, 'Rottweil' );
INSERT INTO wohnort (id,wohnort) VALUES (933, 'Heidelberg' );
INSERT INTO wohnort (id,wohnort) VALUES (934, 'Coswig' );
INSERT INTO wohnort (id,wohnort) VALUES (935, 'Montabaur' );
INSERT INTO wohnort (id,wohnort) VALUES (936, 'Düren' );
INSERT INTO wohnort (id,wohnort) VALUES (937, 'Ueckermünde' );
INSERT INTO wohnort (id,wohnort) VALUES (938, 'Dortmund' );
INSERT INTO wohnort (id,wohnort) VALUES (939, 'Leck' );
INSERT INTO wohnort (id,wohnort) VALUES (940, 'Greven' );
INSERT INTO wohnort (id,wohnort) VALUES (941, 'Altenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (942, 'Metten' );
INSERT INTO wohnort (id,wohnort) VALUES (943, 'Hauenstein' );
INSERT INTO wohnort (id,wohnort) VALUES (944, 'Norderstedt' );
INSERT INTO wohnort (id,wohnort) VALUES (945, 'Niederfüllbach' );
INSERT INTO wohnort (id,wohnort) VALUES (946, 'Ainring' );
INSERT INTO wohnort (id,wohnort) VALUES (947, 'Pliezhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (948, 'Tiefenort' );
INSERT INTO wohnort (id,wohnort) VALUES (949, 'Oelsnitz/Vogtl.' );
INSERT INTO wohnort (id,wohnort) VALUES (950, 'Schnackenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (951, 'Weener' );
INSERT INTO wohnort (id,wohnort) VALUES (952, 'Schwerin' );
INSERT INTO wohnort (id,wohnort) VALUES (953, 'Dallgow-Döberitz' );
INSERT INTO wohnort (id,wohnort) VALUES (954, 'Großwoltersdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (955, 'Hohenpeißenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (956, 'Wegberg' );
INSERT INTO wohnort (id,wohnort) VALUES (957, 'Worms' );
INSERT INTO wohnort (id,wohnort) VALUES (958, 'Rudolstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (959, 'Herrenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (960, 'Hirschstein' );
INSERT INTO wohnort (id,wohnort) VALUES (961, 'Grenzach-Wyhlen' );
INSERT INTO wohnort (id,wohnort) VALUES (962, 'Treuen' );
INSERT INTO wohnort (id,wohnort) VALUES (963, 'Türkenfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (964, 'Vellmar' );
INSERT INTO wohnort (id,wohnort) VALUES (965, 'Hainfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (966, 'Neuenkirchen' );
INSERT INTO wohnort (id,wohnort) VALUES (967, 'Rimsting' );
INSERT INTO wohnort (id,wohnort) VALUES (968, 'Paderborn' );
INSERT INTO wohnort (id,wohnort) VALUES (969, 'Chemnitz' );
INSERT INTO wohnort (id,wohnort) VALUES (970, 'Gangkofen' );
INSERT INTO wohnort (id,wohnort) VALUES (971, 'Wesel' );
INSERT INTO wohnort (id,wohnort) VALUES (972, 'Bad Lauchstädt' );
INSERT INTO wohnort (id,wohnort) VALUES (973, 'Bremen' );
INSERT INTO wohnort (id,wohnort) VALUES (974, 'Emmendingen' );
INSERT INTO wohnort (id,wohnort) VALUES (975, 'Donauwörth' );
INSERT INTO wohnort (id,wohnort) VALUES (976, 'Bamberg' );
INSERT INTO wohnort (id,wohnort) VALUES (977, 'Volkmarsen' );
INSERT INTO wohnort (id,wohnort) VALUES (978, 'Norden' );
INSERT INTO wohnort (id,wohnort) VALUES (979, 'Ahlen' );
INSERT INTO wohnort (id,wohnort) VALUES (980, 'Steinbergkirche' );
INSERT INTO wohnort (id,wohnort) VALUES (981, 'Tegernsee' );
INSERT INTO wohnort (id,wohnort) VALUES (982, 'Tuttlingen' );
INSERT INTO wohnort (id,wohnort) VALUES (983, 'Karlskron' );
INSERT INTO wohnort (id,wohnort) VALUES (984, 'Schönefeld' );
INSERT INTO wohnort (id,wohnort) VALUES (985, 'Halle (Saale)' );
INSERT INTO wohnort (id,wohnort) VALUES (986, 'Extertal' );
INSERT INTO wohnort (id,wohnort) VALUES (987, 'Leidersbach' );
INSERT INTO wohnort (id,wohnort) VALUES (988, 'Dornhan' );
INSERT INTO wohnort (id,wohnort) VALUES (989, 'Bad Neuenahr-Ahrweiler' );
INSERT INTO wohnort (id,wohnort) VALUES (990, 'Osterode am Harz' );
INSERT INTO wohnort (id,wohnort) VALUES (991, 'Heilsbronn' );
INSERT INTO wohnort (id,wohnort) VALUES (992, 'Gernsheim' );
INSERT INTO wohnort (id,wohnort) VALUES (993, 'Wiefelstede' );
INSERT INTO wohnort (id,wohnort) VALUES (994, 'Ostrhauderfehn' );
INSERT INTO wohnort (id,wohnort) VALUES (995, 'Schalkham' );
INSERT INTO wohnort (id,wohnort) VALUES (996, 'Aachen' );
INSERT INTO wohnort (id,wohnort) VALUES (997, 'Mittenwald' );
INSERT INTO wohnort (id,wohnort) VALUES (998, 'Hildesheim' );
INSERT INTO wohnort (id,wohnort) VALUES (999, 'Itzehoe' );
INSERT INTO wohnort (id,wohnort) VALUES (1000, 'Parthenstein' );
INSERT INTO wohnort (id,wohnort) VALUES (1001, 'Geretsried' );
INSERT INTO wohnort (id,wohnort) VALUES (1002, 'Tiefenbronn' );
INSERT INTO wohnort (id,wohnort) VALUES (1003, 'Buttlar' );
INSERT INTO wohnort (id,wohnort) VALUES (1004, 'Buckow (Märkische Schweiz)' );
INSERT INTO wohnort (id,wohnort) VALUES (1005, 'Hohnhorst' );
INSERT INTO wohnort (id,wohnort) VALUES (1006, 'Uedem' );
INSERT INTO wohnort (id,wohnort) VALUES (1007, 'Höhfröschen' );
INSERT INTO wohnort (id,wohnort) VALUES (1008, 'Pegau' );
INSERT INTO wohnort (id,wohnort) VALUES (1009, 'Erding' );
INSERT INTO wohnort (id,wohnort) VALUES (1010, 'Thörnich' );
INSERT INTO wohnort (id,wohnort) VALUES (1011, 'Husum' );
INSERT INTO wohnort (id,wohnort) VALUES (1012, 'Bautzen' );
INSERT INTO wohnort (id,wohnort) VALUES (1013, 'Zossen' );
INSERT INTO wohnort (id,wohnort) VALUES (1014, 'Calau' );
INSERT INTO wohnort (id,wohnort) VALUES (1015, 'Espelkamp' );
INSERT INTO wohnort (id,wohnort) VALUES (1016, 'Kaufbeuren' );
INSERT INTO wohnort (id,wohnort) VALUES (1017, 'Kirchberg (Hunsrück)' );
INSERT INTO wohnort (id,wohnort) VALUES (1018, 'Elsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1019, 'Müncheberg' );
INSERT INTO wohnort (id,wohnort) VALUES (1020, 'Henstedt-Ulzburg' );
INSERT INTO wohnort (id,wohnort) VALUES (1021, 'Irsee' );
INSERT INTO wohnort (id,wohnort) VALUES (1022, 'Bad Münstereifel' );
INSERT INTO wohnort (id,wohnort) VALUES (1023, 'Selters (Taunus)' );
INSERT INTO wohnort (id,wohnort) VALUES (1024, 'Pinneberg' );
INSERT INTO wohnort (id,wohnort) VALUES (1025, 'Würselen' );
INSERT INTO wohnort (id,wohnort) VALUES (1026, 'Altusried' );
INSERT INTO wohnort (id,wohnort) VALUES (1027, 'Damshagen' );
INSERT INTO wohnort (id,wohnort) VALUES (1028, 'Gammelsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1029, 'Feuchtwangen' );
INSERT INTO wohnort (id,wohnort) VALUES (1030, 'Dittelsheim-Heßloch' );
INSERT INTO wohnort (id,wohnort) VALUES (1031, 'Molfsee' );
INSERT INTO wohnort (id,wohnort) VALUES (1032, 'Eggenstein-Leopoldshafen' );
INSERT INTO wohnort (id,wohnort) VALUES (1033, 'Pirmasens' );
INSERT INTO wohnort (id,wohnort) VALUES (1034, 'Bad Berleburg' );
INSERT INTO wohnort (id,wohnort) VALUES (1035, 'Reken' );
INSERT INTO wohnort (id,wohnort) VALUES (1036, 'Grafenau' );
INSERT INTO wohnort (id,wohnort) VALUES (1037, 'Greifenstein' );
INSERT INTO wohnort (id,wohnort) VALUES (1038, 'Hagen' );
INSERT INTO wohnort (id,wohnort) VALUES (1039, 'Vlotho' );
INSERT INTO wohnort (id,wohnort) VALUES (1040, 'Harxheim' );
INSERT INTO wohnort (id,wohnort) VALUES (1041, 'Jettingen-Scheppach' );
INSERT INTO wohnort (id,wohnort) VALUES (1042, 'Wassenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (1043, 'Laubach' );
INSERT INTO wohnort (id,wohnort) VALUES (1044, 'Göppingen' );
INSERT INTO wohnort (id,wohnort) VALUES (1045, 'Drage' );
INSERT INTO wohnort (id,wohnort) VALUES (1046, 'Plettenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (1047, 'Wutha-Farnroda' );
INSERT INTO wohnort (id,wohnort) VALUES (1048, 'Niedenstein' );
INSERT INTO wohnort (id,wohnort) VALUES (1049, 'St. Wendel' );
INSERT INTO wohnort (id,wohnort) VALUES (1050, 'Rohr i.NB' );
INSERT INTO wohnort (id,wohnort) VALUES (1051, 'Wöllstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (1052, 'Memmingen' );
INSERT INTO wohnort (id,wohnort) VALUES (1053, 'Großenhain' );
INSERT INTO wohnort (id,wohnort) VALUES (1054, 'Oberhausen-Rheinhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (1055, 'Gräfenhainichen' );
INSERT INTO wohnort (id,wohnort) VALUES (1056, 'Weißenfels' );
INSERT INTO wohnort (id,wohnort) VALUES (1057, 'Wusterhausen/Dosse' );
INSERT INTO wohnort (id,wohnort) VALUES (1058, 'Osterberg' );
INSERT INTO wohnort (id,wohnort) VALUES (1059, 'Euskirchen' );
INSERT INTO wohnort (id,wohnort) VALUES (1060, 'Bülkau' );
INSERT INTO wohnort (id,wohnort) VALUES (1061, 'Simmelsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1062, 'Kösching' );
INSERT INTO wohnort (id,wohnort) VALUES (1063, 'Varel' );
INSERT INTO wohnort (id,wohnort) VALUES (1064, 'Duisburg' );
INSERT INTO wohnort (id,wohnort) VALUES (1065, 'Frauenneuharting' );
INSERT INTO wohnort (id,wohnort) VALUES (1066, 'Karlsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1067, 'Unna' );
INSERT INTO wohnort (id,wohnort) VALUES (1068, 'Lindhorst' );
INSERT INTO wohnort (id,wohnort) VALUES (1069, 'Monreal' );
INSERT INTO wohnort (id,wohnort) VALUES (1070, 'Uffenheim' );
INSERT INTO wohnort (id,wohnort) VALUES (1071, 'St. Gallen, Schweiz' );
INSERT INTO wohnort (id,wohnort) VALUES (1072, 'Osnabrück' );
INSERT INTO wohnort (id,wohnort) VALUES (1073, 'Kandel' );
INSERT INTO wohnort (id,wohnort) VALUES (1074, 'Vreden' );
INSERT INTO wohnort (id,wohnort) VALUES (1075, 'Niestetal' );
INSERT INTO wohnort (id,wohnort) VALUES (1076, 'Wismar' );
INSERT INTO wohnort (id,wohnort) VALUES (1077, 'Obergünzburg' );
INSERT INTO wohnort (id,wohnort) VALUES (1078, 'Waiblingen' );
INSERT INTO wohnort (id,wohnort) VALUES (1079, 'Cottbus' );
INSERT INTO wohnort (id,wohnort) VALUES (1080, 'Theilheim' );
INSERT INTO wohnort (id,wohnort) VALUES (1081, 'Bad Sulza' );
INSERT INTO wohnort (id,wohnort) VALUES (1082, 'Nesse-Apfelstädt' );
INSERT INTO wohnort (id,wohnort) VALUES (1083, 'Horb am Neckar' );
INSERT INTO wohnort (id,wohnort) VALUES (1084, 'Wingst' );
INSERT INTO wohnort (id,wohnort) VALUES (1085, 'Altenstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (1086, 'Radebeul' );
INSERT INTO wohnort (id,wohnort) VALUES (1087, 'Plauen' );
INSERT INTO wohnort (id,wohnort) VALUES (1088, 'Bottrop' );
INSERT INTO wohnort (id,wohnort) VALUES (1089, 'Schorndorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1090, 'Kirchdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1091, 'Neumünster' );
INSERT INTO wohnort (id,wohnort) VALUES (1092, 'Filderstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (1093, 'Eichenzell' );
INSERT INTO wohnort (id,wohnort) VALUES (1094, 'Hirschaid' );
INSERT INTO wohnort (id,wohnort) VALUES (1095, 'Bassum' );
INSERT INTO wohnort (id,wohnort) VALUES (1096, 'Telgte' );
INSERT INTO wohnort (id,wohnort) VALUES (1097, 'Alsheim' );
INSERT INTO wohnort (id,wohnort) VALUES (1098, 'Haunetal' );
INSERT INTO wohnort (id,wohnort) VALUES (1099, 'Fluorn-Winzeln' );
INSERT INTO wohnort (id,wohnort) VALUES (1100, 'Haiger' );
INSERT INTO wohnort (id,wohnort) VALUES (1101, 'Karben' );
INSERT INTO wohnort (id,wohnort) VALUES (1102, 'Herdwangen-Schönach' );
INSERT INTO wohnort (id,wohnort) VALUES (1103, 'Leverkusen' );
INSERT INTO wohnort (id,wohnort) VALUES (1104, 'Aerzen' );
INSERT INTO wohnort (id,wohnort) VALUES (1105, 'Wachtendonk' );
INSERT INTO wohnort (id,wohnort) VALUES (1106, 'Lüneburg' );
INSERT INTO wohnort (id,wohnort) VALUES (1107, 'Saarbrücken' );
INSERT INTO wohnort (id,wohnort) VALUES (1108, 'Lichtenau' );
INSERT INTO wohnort (id,wohnort) VALUES (1109, 'Tostedt' );
INSERT INTO wohnort (id,wohnort) VALUES (1110, 'Elchesheim-Illingen' );
INSERT INTO wohnort (id,wohnort) VALUES (1111, 'Ratingen' );
INSERT INTO wohnort (id,wohnort) VALUES (1112, 'Gifhorn' );
INSERT INTO wohnort (id,wohnort) VALUES (1113, 'Ludwigslust' );
INSERT INTO wohnort (id,wohnort) VALUES (1114, 'Kleinrinderfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (1115, 'Neuwittenbek' );
INSERT INTO wohnort (id,wohnort) VALUES (1116, 'Halberstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (1117, 'Ebersberg' );
INSERT INTO wohnort (id,wohnort) VALUES (1118, 'Tröstau' );
INSERT INTO wohnort (id,wohnort) VALUES (1119, 'Reinfeld (Holstein)' );
INSERT INTO wohnort (id,wohnort) VALUES (1120, 'Bad Breisig' );
INSERT INTO wohnort (id,wohnort) VALUES (1121, 'Xanten' );
INSERT INTO wohnort (id,wohnort) VALUES (1122, 'Konradsreuth' );
INSERT INTO wohnort (id,wohnort) VALUES (1123, 'Altenholz' );
INSERT INTO wohnort (id,wohnort) VALUES (1124, 'Karlsfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (1125, 'Unterhaching' );
INSERT INTO wohnort (id,wohnort) VALUES (1126, 'Neu-Isenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (1127, 'Löhne' );
INSERT INTO wohnort (id,wohnort) VALUES (1128, 'Esens' );
INSERT INTO wohnort (id,wohnort) VALUES (1129, 'Lauda-Königshofen' );
INSERT INTO wohnort (id,wohnort) VALUES (1130, 'Kirchzarten' );
INSERT INTO wohnort (id,wohnort) VALUES (1131, 'Osterholz-Scharmbeck' );
INSERT INTO wohnort (id,wohnort) VALUES (1132, 'Neuburg a.d.Donau' );
INSERT INTO wohnort (id,wohnort) VALUES (1133, 'Lychen' );
INSERT INTO wohnort (id,wohnort) VALUES (1134, 'Wernberg-Köblitz' );
INSERT INTO wohnort (id,wohnort) VALUES (1135, 'Dossenheim' );
INSERT INTO wohnort (id,wohnort) VALUES (1136, 'Lauenburg/ Elbe' );
INSERT INTO wohnort (id,wohnort) VALUES (1137, 'Sindelfingen' );
INSERT INTO wohnort (id,wohnort) VALUES (1138, 'Güstrow' );
INSERT INTO wohnort (id,wohnort) VALUES (1139, 'Neusäß' );
INSERT INTO wohnort (id,wohnort) VALUES (1140, 'Seiffen/Erzgeb.' );
INSERT INTO wohnort (id,wohnort) VALUES (1141, 'Römerstein' );
INSERT INTO wohnort (id,wohnort) VALUES (1142, 'Nandlstadt' );
INSERT INTO wohnort (id,wohnort) VALUES (1143, 'Weihenzell' );
INSERT INTO wohnort (id,wohnort) VALUES (1144, 'Ostfildern' );
INSERT INTO wohnort (id,wohnort) VALUES (1145, 'Rangsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1146, 'Peine' );
INSERT INTO wohnort (id,wohnort) VALUES (1147, 'Menden (Sauerland)' );
INSERT INTO wohnort (id,wohnort) VALUES (1148, 'Mamming' );
INSERT INTO wohnort (id,wohnort) VALUES (1149, 'Gotha' );
INSERT INTO wohnort (id,wohnort) VALUES (1150, 'Wehnde' );
INSERT INTO wohnort (id,wohnort) VALUES (1151, 'Schönaich' );
INSERT INTO wohnort (id,wohnort) VALUES (1152, 'Deggendorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1153, 'Babenhausen' );
INSERT INTO wohnort (id,wohnort) VALUES (1154, 'Niederwiesa' );
INSERT INTO wohnort (id,wohnort) VALUES (1155, 'Mölln' );
INSERT INTO wohnort (id,wohnort) VALUES (1156, 'Massen-Niederlausitz' );
INSERT INTO wohnort (id,wohnort) VALUES (1157, 'Hagen im Bremischen' );
INSERT INTO wohnort (id,wohnort) VALUES (1158, 'Wenden' );
INSERT INTO wohnort (id,wohnort) VALUES (1159, 'Offenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (1160, 'Gimbsheim' );
INSERT INTO wohnort (id,wohnort) VALUES (1161, 'Reichenbach-Steegen' );
INSERT INTO wohnort (id,wohnort) VALUES (1162, 'Alt Schwerin' );
INSERT INTO wohnort (id,wohnort) VALUES (1163, 'Sarstedt' );
INSERT INTO wohnort (id,wohnort) VALUES (1164, 'Goch' );
INSERT INTO wohnort (id,wohnort) VALUES (1165, 'Beckingen' );
INSERT INTO wohnort (id,wohnort) VALUES (1166, 'Amt Wachsenburg' );
INSERT INTO wohnort (id,wohnort) VALUES (1167, 'Tessin' );
INSERT INTO wohnort (id,wohnort) VALUES (1168, 'Oelsnitz/Erzgeb.' );
INSERT INTO wohnort (id,wohnort) VALUES (1169, 'Rotenburg (Wümme)' );
INSERT INTO wohnort (id,wohnort) VALUES (1170, 'Beverungen' );
INSERT INTO wohnort (id,wohnort) VALUES (1171, 'Groß-Gerau' );
INSERT INTO wohnort (id,wohnort) VALUES (1172, 'Schüttorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1173, 'Denklingen' );
INSERT INTO wohnort (id,wohnort) VALUES (1174, 'Havixbeck' );
INSERT INTO wohnort (id,wohnort) VALUES (1175, 'Leopoldshöhe' );
INSERT INTO wohnort (id,wohnort) VALUES (1176, 'Heusweiler' );
INSERT INTO wohnort (id,wohnort) VALUES (1177, 'Gaildorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1178, 'Gilching' );
INSERT INTO wohnort (id,wohnort) VALUES (1179, 'Schliengen' );
INSERT INTO wohnort (id,wohnort) VALUES (1180, 'Köln' );
INSERT INTO wohnort (id,wohnort) VALUES (1181, 'Mettmann' );
INSERT INTO wohnort (id,wohnort) VALUES (1182, 'Flensburg' );
INSERT INTO wohnort (id,wohnort) VALUES (1183, 'Berchtesgaden' );
INSERT INTO wohnort (id,wohnort) VALUES (1184, 'Senden' );
INSERT INTO wohnort (id,wohnort) VALUES (1185, 'Olching' );
INSERT INTO wohnort (id,wohnort) VALUES (1186, 'Lauf a.d.Pegnitz' );
INSERT INTO wohnort (id,wohnort) VALUES (1187, 'Bayreuth' );
INSERT INTO wohnort (id,wohnort) VALUES (1188, 'Rüdersdorf bei Berlin' );
INSERT INTO wohnort (id,wohnort) VALUES (1189, 'Bingen am Rhein' );
INSERT INTO wohnort (id,wohnort) VALUES (1190, 'Weiding' );
INSERT INTO wohnort (id,wohnort) VALUES (1191, 'Jever' );
INSERT INTO wohnort (id,wohnort) VALUES (1192, 'Weitramsdorf' );
INSERT INTO wohnort (id,wohnort) VALUES (1193, 'Dasing' );
INSERT INTO wohnort (id,wohnort) VALUES (1194, 'Teutschenthal' );
INSERT INTO wohnort (id,wohnort) VALUES (1195, 'Grünhain-Beierfeld' );
INSERT INTO wohnort (id,wohnort) VALUES (1196, 'Strehla' );
INSERT INTO wohnort (id,wohnort) VALUES (1197, 'Soest' );
INSERT INTO wohnort (id,wohnort) VALUES (1198, 'Bruchsal' );
INSERT INTO wohnort (id,wohnort) VALUES (1199, 'Karstädt' );
INSERT INTO wohnort (id,wohnort) VALUES (1200, 'Bergen' );
INSERT INTO wohnort (id,wohnort) VALUES (1201, 'Maßbach' );
INSERT INTO wohnort (id,wohnort) VALUES (1202, 'Pfaffenhofen a.d.Ilm' );
INSERT INTO wohnort (id,wohnort) VALUES (1203, 'Legau' );
INSERT INTO wohnort (id,wohnort) VALUES (1204, 'Lohsa' );
INSERT INTO wohnort (id,wohnort) VALUES (1205, 'Hofgeismar' );
INSERT INTO wohnort (id,wohnort) VALUES (1206, 'Kirchberg an der Murr' );
INSERT INTO wohnort (id,wohnort) VALUES (1207, 'Ellerau' );
INSERT INTO wohnort (id,wohnort) VALUES (1208, 'Eisenach' );
INSERT INTO wohnort (id,wohnort) VALUES (1209, 'Wirges' );
INSERT INTO wohnort (id,wohnort) VALUES (1210, 'Arnstein' );
INSERT INTO wohnort (id,wohnort) VALUES (1211, 'Herford' );
INSERT INTO wohnort (id,wohnort) VALUES (1212, 'Neustrelitz' );
INSERT INTO wohnort (id,wohnort) VALUES (1213, 'Donaueschingen' );
INSERT INTO wohnort (id,wohnort) VALUES (1214, 'Fürth' );
INSERT INTO wohnort (id,wohnort) VALUES (1215, 'Rettenberg' );
INSERT INTO wohnort (id,wohnort) VALUES (1216, 'Tengen' );
INSERT INTO wohnort (id,wohnort) VALUES (1217, 'Poseritz' );
INSERT INTO wohnort (id,wohnort) VALUES (1218, 'Kolbermoor' );
INSERT INTO wohnort (id,wohnort) VALUES (1219, 'Warstein' );
