endpoints:
  env:
    - keys-to-sanitize: "password"
    - keys-to-sanitize: "secret"
    - keys-to-sanitize: "key"
    - keys-to-sanitize: "passwort"
  health:
    sensitive: false
  endpoints:
    shutdown:
      enabled: false
server:
  error:
    path: /fehler
  compression:
    enabled: true
    min-response-size: 2048
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL94Dialect
info:
  application:
    artifactId: @project.artifactId@
    description: @project.description@
    groupId: @project.groupId@
    name: @project.name@
    version: @project.version@
management:
  address: 127.0.0.1
  context-path: "/manage"
  security:
    enabled: true
spring:
  application:
    admin:
      enabled: false
    name: @project.name@
  datasource:
    driverClassName: org.postgresql.Driver
    platform: POSTGRESQL
    tomcat:
      max-active: 20
    url: ${DATABASE_URL}
    continue-on-error: true
    schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
  session:
    store-type: jdbc
    jdbc:
      initializer:
        enabled: true
  devtools:
    livereload:
      enabled: false
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: ${BTW17_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  template:
    cache: false
  thymeleaf:
    cache: false
btw17:
  kandidaten:
    pageSize: 20
    loginUsername: ${BTW17_LOGIN_USERNAME}
    loginPassword: ${BTW17_LOGIN_PASSWORD}
    googleMapsApiKey: ${BTW17_GOOGLE_APS_API_KEY}
    googleAnalyticsKey: ${BTW17_GOOGLE_ANALYTICS_ID}
    googleSiteVerification: ${BTW17_GOOGLE_WEBMASTER_TOOLS_ID}
    msvalidateKey: ${BTW17_MICROSOFT_WEBMASTER_TOOLS_ID}
    facebookAppId: ${BTW17_FACEBOOK_APP_ID}
    twitterCardSite: ${BTW17_TWITTER_CARD_SITE}
    twitterCardCreator: ${BTW17_TWITTER_CARD_CREATOR}
    connTimeToLive: 10
    maxIdleTime: 120
    millisToWaitBetweenTwoApiCalls: 1000
    checkFotoUrl: false
    pageSubTitle: Bundestagswahl 2017 - Alle 2559 Direktkandidaten
    webSecurityConfigPublicPaths:
      - "/"
      - "/kandidat/all"
      - "/kandidat/**"
      - "/beruf/all"
      - "/berufsgruppe/all"
      - "/bundesland/all"
      - "/geburtsort/all"
      - "/listepartei/all"
      - "/partei/all"
      - "/kandidat/all"
      - "/wahlkreis/all"
      - "/wahlperiode/all"
      - "/wohnort/all"
      - "/beruf/**"
      - "/berufsgruppe/**"
      - "/bundesland/**"
      - "/geburtsort/**"
      - "/listepartei/**"
      - "/partei/**"
      - "/kandidat/**"
      - "/wahlkreis/**"
      - "/wahlperiode/**"
      - "/wohnort/**"
      - "/mdb/**"
      - "/webseite/agentur/all"
      - "/webseite/agentur/**"
      - "/webseite/cms/all"
      - "/webseite/cms/**"
      - "/landesliste/**"
      - "/landesliste/bundesland/**"
      - "/landesliste/listepartei/**"
      - "/regierung/kanzleramt"
      - "/geburtsjahr/**"
      - "/imprint"
      - "/welcome"
      - "/fehler"
      - "/datenschutz"
      - "/suche/formular"
      - "/suche/freitext/formular"
      - "/fraktion/all"
      - "/fraktion/**"
      - "/ministerium/all"
      - "/ministerium/**"
      - "/ausschuss/all"
      - "/ausschuss/**"
      - "/img/*"
      - "/img/**"
      - "/css/*"
      - "/css/**"
      - "/favicon/*"
      - "/favicon/**"
      - "/js/*"
      - "/js/**"
      - "/map-icons/*"
      - "/map-icons/**"
      - "/webjars/*"
      - "/webjars/**"
    urlPrefixForKandidatFoto:
      - "https://www.abgeordnetenwatch.de/sites/abgeordnetenwatch.de/files/styles/large/public/"
      - "https://www.abgeordnetenwatch.de/sites/abgeordnetenwatch.de/files/styles/large/public/users/"
      - "https://www.abgeordnetenwatch.de/sites/abgeordnetenwatch.de/files/styles/media_thumbnail/public/users/"
    tableContent:
      countAusschuss: 48
      countBeruf: 3746
      countBerufsgruppe: 55
      countBundesland: 16
      countFraktion: 4
      countGeburtsort: 1601
      countPartei: 142
      countListePartei: 27
      countMinisterium: 13
      countWahlkreis: 299
      countWohnort: 1816
      countLandesListe: 118
      countKandidatFlat: 2559
      countKandidat: 2559
      countWebseiteAgentur: 5
      countWebseiteCms: 8
      countBtw17Ergebnis: 0
      countBtw17KandidatFlat: 0
      countBtw17Strukturdaten: 0
      countBtw17Wahlbewerber: 0
      countBtw17Wahlkreis: 0
      #countBtw17Ergebnis: 0
      #countBtw17KandidatFlat: 0
      #countBtw17Strukturdaten: 0
      #countBtw17Wahlbewerber: 0
      #countBtw17Wahlkreis: 0
---
spring:
  profiles: default
---
spring:
  profiles: travis
  datasource:
    url: 'jdbc:postgresql://localhost:5432/kandidatentravis?user=jdbc&password=jdbcpwd&schema=public'
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  compression:
    enabled: false
btw17:
  kandidaten:
    checkFotoUrl: false
---
spring:
  profiles: releasing
  datasource:
    url: 'jdbc:postgresql://localhost:5432/kandidatenreleasing?user=jdbc&password=jdbcpwd&schema=public'
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  compression:
    enabled: false
btw17:
  kandidaten:
    checkFotoUrl: false
---
spring:
  profiles: devtest
  datasource:
    url: 'jdbc:postgresql://localhost:5432/kandidatendevtest?user=jdbc&password=jdbcpwd&schema=public'
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  compression:
    enabled: false
btw17:
  kandidaten:
    checkFotoUrl: false
logging:
  config: classpath:logback-devtest.xml
  file: logging-devtest.log
  level:
    org:
      woehlke:
        btw17:
          kandidaten:
            oodm:
              bundeswahlleiter:
                file2db: DEBUG
                model: DEBUG
                service: DEBUG
