endpoints:
  env:
    - keys-to-sanitize: "password"
    - keys-to-sanitize: "secret"
    - keys-to-sanitize: "key"
    - keys-to-sanitize: "passwort"
  health:
    sensitive: false
  endpoints:
    shutdown:
      enabled: false
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL94Dialect
info:
  application:
    artifactId: @project.artifactId@
    description: @project.description@
    groupId: @project.groupId@
    name: @project.name@
    version: @project.version@
management:
  address: 127.0.0.1
  context-path: "/manage"
  security:
    enabled: false
spring:
  application:
    admin:
      enabled: false
    name: @project.name@
  datasource:
    driverClassName: org.postgresql.Driver
    max-total: 20
    maxActive: 20
    platform: POSTGRESQL
    tomcat:
      max-active: 20
    #url: jdbc:postgresql://localhost:5432/kandidaten?user=kandidaten&password=kandidatenpwd
    url: ${DATABASE_URL}
    continue-on-error: true
  devtools:
    livereload:
      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      #ddl-auto: create-drop
      #ddl-auto: update
      ddl-auto: ${BTW17_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
  template:
    cache: false
  thymeleaf:
    cache: false
btw17:
  kandidaten:
    pageSize: 20
    loginUsername: ${BTW17_LOGIN_USERNAME}
    loginPassword: ${BTW17_LOGIN_PASSWORD}
    #loginUsername: blubb
    #loginPassword: blablabla
    googleMapsApiKey: ${BTW17_GOOGLE_APS_API_KEY}
    googleAnalyticsKey: ${BTW17_GOOGLE_ANALYTICS_ID}
    connTimeToLive: 10
    maxIdleTime: 120
    millisToWaitBetweenTwoApiCalls: 1000
    checkFotoUrl: false
    pageSubTitle: Bundestagswahl 2017 - Alle 2559 Direktkandidaten
    twitterCardSite: port80guru
    twitterCardCreator: port80guru
    webSecurityConfigPublicPaths:
      - "/"
      - "/kandidat/all"
      - "/kandidat/**"
      - "/kandidatflat/all"
      - "/kandidatflat/**"
      - "/beruf/all"
      - "/berufsgruppe/all"
      - "/bundesland/all"
      - "/geburtsort/all"
      - "/listepartei/all"
      - "/partei/all"
      - "/kandidat/all"
      - "/wahlkreis/all"
      - "/wohnort/all"
      - "/beruf/**"
      - "/berufsgruppe/**"
      - "/bundesland/**"
      - "/geburtsort/**"
      - "/listepartei/**"
      - "/partei/**"
      - "/kandidat/**"
      - "/wahlkreis/**"
      - "/wohnort/**"
      - "/mdb/**"
      - "/landesliste/**"
      - "/landesliste/bundesland/**"
      - "/landesliste/listepartei/**"
      - "/geburtsjahr/**"
      - "/imprint"
      - "/welcome"
      - "/suche/formular"
      - "/suche/freitext/formular"
      - "/fraktion/all"
      - "/fraktion/**"
      - "/ministerium/all"
      - "/ministerium/**"
      - "/ausschuss/all"
      - "/ausschuss/**"
      - "/img/*"
      - "/img/**"
      - "/css/*"
      - "/css/**"
      - "/favicon/*"
      - "/favicon/**"
      - "/js/*"
      - "/js/**"
      - "/map-icons/*"
      - "/map-icons/**"
      - "/webjars/*"
      - "/webjars/**"
    urlPrefixForKandidatFoto:
      - "https://www.abgeordnetenwatch.de/sites/abgeordnetenwatch.de/files/styles/large/public/"
      - "https://www.abgeordnetenwatch.de/sites/abgeordnetenwatch.de/files/styles/large/public/users/"
      - "https://www.abgeordnetenwatch.de/sites/abgeordnetenwatch.de/files/styles/media_thumbnail/public/users/"
    tableContent:
      countBeruf: 1211
      countBerufsgruppe: 55
      countBundesland: 16
      countGeburtsort: 1081
      countPartei: 134
      countWahlkreis: 299
      countWohnort: 1219
      countLandesListe: 118
      countKandidatFlat: 2559
      countKandidat: 2559
---
spring:
  profiles: testing
  datasource:
    url: ${DATABASE_URL_TEST}
    #url: jdbc:postgresql://localhost:5432/kandidaten?user=kandidaten&password=kandidatenpwd
btw17:
  kandidaten:
    checkFotoUrl: false
---
spring:
  profiles: travis
  datasource:
    driverClassName: org.h2.Driver
    platform: H2
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
btw17:
  kandidaten:
    checkFotoUrl: false