endpoints:
  env:
    - keys-to-sanitize: "password"
    - keys-to-sanitize: "secret"
    - keys-to-sanitize: "key"
    - keys-to-sanitize: "passwort"
  health:
    sensitive: false
  endpoints:
    shutdown:
      enabled: false
server:
  error:
    path: /fehler
  compression:
    enabled: true
    min-response-size: 2048
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL94Dialect
info:
  application:
    artifactId: @project.artifactId@
    description: @project.description@
    groupId: @project.groupId@
    name: @project.name@
    version: @project.version@
management:
  address: 127.0.0.1
  context-path: "/manage"
  security:
    enabled: true
spring:
  application:
    admin:
      enabled: false
    name: @project.name@
  datasource:
    driverClassName: org.postgresql.Driver
    #max-total: 20
    #maxActive: 20
    platform: POSTGRESQL
    tomcat:
      max-active: 20
    url: ${DATABASE_URL}
    continue-on-error: true
    schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
  session:
    store-type: jdbc
    jdbc:
      initializer:
        enabled: true
  devtools:
    livereload:
      enabled: false
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: ${BTW17_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  template:
    cache: false
  thymeleaf:
    cache: false
btw17:
  kandidaten:
    pageSize: 20
    loginUsername: ${BTW17_LOGIN_USERNAME}
    loginPassword: ${BTW17_LOGIN_PASSWORD}
    googleMapsApiKey: ${BTW17_GOOGLE_APS_API_KEY}
    googleAnalyticsKey: ${BTW17_GOOGLE_ANALYTICS_ID}
    googleSiteVerification: ${BTW17_GOOGLE_WEBMASTER_TOOLS_ID}
    msvalidateKey: ${BTW17_MICROSOFT_WEBMASTER_TOOLS_ID}
    facebookAppId: ${BTW17_FACEBOOK_APP_ID}
    twitterCardSite: ${BTW17_TWITTER_CARD_SITE}
    twitterCardCreator: ${BTW17_TWITTER_CARD_CREATOR}
    connTimeToLive: 10
    maxIdleTime: 120
    millisToWaitBetweenTwoApiCalls: 1000
    checkFotoUrl: false
    pageSubTitle: Bundestagswahl 2017 - Alle 2559 Direktkandidaten
    webSecurityConfigPublicPaths:
      - "/"
      - "/kandidat/all"
      - "/kandidat/**"
      - "/beruf/all"
      - "/berufsgruppe/all"
      - "/bundesland/all"
      - "/geburtsort/all"
      - "/listepartei/all"
      - "/partei/all"
      - "/kandidat/all"
      - "/wahlkreis/all"
      - "/wohnort/all"
      - "/beruf/**"
      - "/berufsgruppe/**"
      - "/bundesland/**"
      - "/geburtsort/**"
      - "/listepartei/**"
      - "/partei/**"
      - "/kandidat/**"
      - "/wahlkreis/**"
      - "/wohnort/**"
      - "/mdb/**"
      - "/webseite/agentur/all"
      - "/webseite/agentur/**"
      - "/webseite/cms/all"
      - "/webseite/cms/**"
      - "/landesliste/**"
      - "/landesliste/bundesland/**"
      - "/landesliste/listepartei/**"
      - "/regierung/kanzleramt"
      - "/geburtsjahr/**"
      - "/imprint"
      - "/welcome"
      - "/fehler"
      - "/datenschutz"
      - "/suche/formular"
      - "/suche/freitext/formular"
      - "/fraktion/all"
      - "/fraktion/**"
      - "/ministerium/all"
      - "/ministerium/**"
      - "/ausschuss/all"
      - "/ausschuss/**"
      - "/img/*"
      - "/img/**"
      - "/css/*"
      - "/css/**"
      - "/favicon/*"
      - "/favicon/**"
      - "/js/*"
      - "/js/**"
      - "/map-icons/*"
      - "/map-icons/**"
      - "/webjars/*"
      - "/webjars/**"
    urlPrefixForKandidatFoto:
      - "https://www.abgeordnetenwatch.de/sites/abgeordnetenwatch.de/files/styles/large/public/"
      - "https://www.abgeordnetenwatch.de/sites/abgeordnetenwatch.de/files/styles/large/public/users/"
      - "https://www.abgeordnetenwatch.de/sites/abgeordnetenwatch.de/files/styles/media_thumbnail/public/users/"
    tableContent:
      countBeruf: 1211
      countBerufsgruppe: 55
      countBundesland: 16
      countGeburtsort: 1081
      countPartei: 134
      countWahlkreis: 299
      countWohnort: 1219
      countLandesListe: 118
      countKandidatFlat: 2559
      countKandidat: 2559
---
logging:
  file: testing.log.txt
spring:
  profiles: testing
  datasource:
    url: ${DATABASE_URL_TEST}
    continue-on-error: true
  jpa:
    show-sql: false
server:
  compression:
    enabled: false
btw17:
  kandidaten:
    checkFotoUrl: false
---
spring:
  profiles: travis
  datasource:
    url: 'jdbc:postgresql://localhost:5432/kandidatentest?user=kandidatentest&password=kandidatentestpwd'
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  compression:
    enabled: false
btw17:
  kandidaten:
    checkFotoUrl: false
---
logging:
  file: testing.log.txt
spring:
  profiles: development
  datasource:
    url: 'jdbc:postgresql://localhost:5432/kandidatentest?user=kandidatentest&password=kandidatentestpwd'
    continue-on-error: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  compression:
    enabled: false
btw17:
  kandidaten:
    checkFotoUrl: false
---
logging:
  file: travis.log.txt
server:
  compression:
    enabled: false
spring:
  h2:
    console:
      enabled: false
  profiles: travis-old
  datasource:
    driverClassName: org.h2.Driver
    platform: H2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    schema: classpath:org/springframework/session/jdbc/schema-h2.sql
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
btw17:
  kandidaten:
    checkFotoUrl: false